<!-- # Libraries -->

In [1]:
import os, getpass, textwrap, time, uuid
from dotenv import load_dotenv # type: ignore

# from langchain_community.callbacks import get_openai_callback # type: ignore
# from langchain_core.runnables import RunnablePassthrough # type: ignore
# from langchain_core.output_parsers import StrOutputParser # type: ignore

# from langchain_groq import ChatGroq # type: ignore

In [2]:
# Load environment variables from .env file
load_dotenv()

True

In [ ]:
import nest_asyncio # type: ignore
nest_asyncio.apply()

<!-- # Helper Function -->

In [4]:
def pprint_docs(docs):
    print(f"\n{'-' * 70}\n".join([f"Document {i+1}:\n\n" + "\n".join(textwrap.wrap(d.page_content)) for i, d in enumerate(docs)]))

def pprint_result(result):
    print("Answer: " + "\n".join(textwrap.wrap(result)))

<!-- # Parsing Document to Markdown Format -->

# Convert PDF to Markdown format w Llama Parse

In [ ]:
# import os
# import logging
# from llama_cloud_services import LlamaParse

# # Setup logging
# logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(message)s')
# logger = logging.getLogger(__name__)

# # Initialize parser
# parser = LlamaParse(
#     result_type="markdown",
#     parse_mode="parse_page_with_agent", 
#     preserve_layout_alignment_across_pages=True,
#     system_prompt="ini adalah dokumen pedoman Sistem Pemerintahan Berbasis Elektronik (SPBE). Didalamnya ada 4 Domain yang disingkat D (contoh: D1,D2,D3,D4), lalu ada 8 Aspek yang disingkat A (contoh: A2, A5) dan 47 Indikator yang disingkat ID (contoh: ID-3, ID-23). jadi struktur dari SPBE ada 3 unsur tadi domain, aspek, dan indikator, dan penilaian indikator ada kriteria level nya yaitu level 1-5,  dengan level 5 paling tinggi nya.\n\nakan ada perlakuan khusus saat kamu extract table pedoman SPBE ini:\n1. pada table tingkat pertama yaitu penjelasan kuesioner Domain, Aspek, dan Indikator keberapa nya, dari penjelasan, deskripsi indikator, ketentuan penilaian, dan contoh bukti dukung. ini harus dalam 1 tingkatan markdown\n2. pada table tingkat kedua yaitu penjelasan kriteria level dari suatu indikator, kriteria pemenuhan Level, kriteria bukti dukung, tolong bagi seperti itu pada tingkatan table ini",
#     language="id",
#     adaptive_long_table=True,
#     compact_markdown_table=True,
#     model="gemini-2.0-flash-001"
# )

# # Parse PDF and get markdown content
# markdown_content = parser.load_data("data/5. Pedoman Menteri PANRB NO 3 Tahun 2024 Pedoman Tata Cara Pemantauan dan Evaluasi SPBE.pdf")

# # Save markdown content to file
# output_path = "data/parsed_5. Pedoman Menteri PANRB NO 3 Tahun 2024 Pedoman Tata Cara Pemantauan dan Evaluasi SPBE.md"
# with open(output_path, "w", encoding="utf-8") as f:
#     for doc in markdown_content:
#         f.write(doc.text + "\n")

# logger.info(f"Markdown content saved to {output_path}")

<!-- # Load Markdown File -->

# Load Markdown file

In [5]:
from langchain_community.document_loaders import UnstructuredMarkdownLoader # type: ignore
from langchain_core.documents import Document # type: ignore

markdown_path = "data/parsed_5. Pedoman Menteri PANRB NO 3 Tahun 2024 Pedoman Tata Cara Pemantauan dan Evaluasi SPBE.md" 
loader = UnstructuredMarkdownLoader(markdown_path, mode="elements")

spbe_md = loader.load()
print(f"Number of documents: {len(spbe_md)}\n")

for document in spbe_md[:50]:
    print(f"{document.page_content}\n")

Number of documents: 1826

SALINAN

MENTERI PENDAYAGUNAAN APARATUR NEGARA DAN REFORMASI BIROKRASI REPUBLIK INDONESIA

PEDOMAN MENTERI PENDAYAGUNAAN APARATUR NEGARA DAN REFORMASI BIROKRASI REPUBLIK INDONESIA NOMOR 3 TAHUN 2024 TENTANG TATA CARA PEMANTAUAN DAN EVALUASI SISTEM PEMERINTAHAN BERBASIS ELEKTRONIK

DENGAN RAHMAT TUHAN YANG MAHA ESA

MENTERI PENDAYAGUNAAN APARATUR NEGARA DAN REFORMASI BIROKRASI REPUBLIK INDONESIA,

BAB I PENDAHULUAN

A. Latar Belakang

Sistem Pemerintahan Berbasis Elektronik (SPBE) merupakan penyelenggaraan pemerintahan yang memanfaatkan teknologi informasi dan komunikasi dalam rangka meningkatkan kualitas layanan administrasi pemerintahan dan pelayanan publik yang efisien dan optimal, merupakan amanat pelaksanaan Peraturan Presiden Republik Indonesia Nomor 95 Tahun 2018 tentang Sistem Pemerintahan Berbasis Elektronik (Perpres SPBE). Pelaksanaan SPBE menjadi fondasi serta sebagai pengungkit (enabler) dari reformasi birokrasi melalui pelaksanaan transformasi digital dan Satu Data Indonesia (SDI) serta menjadi salah satu aspek dalam reformasi birokrasi tematik yakni digitalisasi administrasi pemerintahan. Melalui penerapan SPBE secara terpadu dan menyeluruh, diharapkan dapat menciptakan birokrasi pemerintah yang integratif, dinamis, transparan, dan inovatif pada Instansi Pusat dan Pemerintah Daerah.

Upaya untuk mendorong perkembangan keterpaduan penerapan SPBE pada Instansi Pusat dan Pemerintah Daerah dilakukan melalui penerapan Arsitektur SPBE. Arsitektur SPBE Nasional telah ditetapkan melalui Peraturan Presiden Nomor 132 Tahun 2022 tentang Arsitektur SPBE Nasional, sehingga pembangunan layanan digital pada Instansi Pusat dan Pemerintah Daerah harus selaras dengan Arsitektur SPBE Nasional. Selain itu, pada tahun 2023 telah ditetapkan Peraturan Presiden Nomor 82 Tahun 2023 tentang Percepatan Transformasi Digital dan Keterpaduan Layanan Digital Nasional, yang menjadi salah satu dasar penyesuaian pedoman dalam rangka pelaksanaan pemantauan dan evaluasi SPBE.

Dalam rangka memastikan penerapan SPBE yang menjadi peran pembinaan dan pengawasan oleh Tim Koordinasi SPBE Nasional, maka dilakukan kegiatan pemantauan dan evaluasi SPBE. Pada tahun 2020, Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi (PANRB) Selaku Ketua Tim Koordinasi SPBE Nasional, telah melakukan penyempurnaan pedoman dan instrumen untuk mengukur tingkat kematangan (maturity level) penerapan SPBE pada Instansi Pusat dan Pemerintah Daerah, melalui Peraturan Menteri PANRB Nomor 59 Tahun 2020 tentang Pemantauan dan Evaluasi Sistem Pemerintahan Berbasis Elektronik. Dengan adanya Peraturan Menteri sebagaimana dimaksud, diharapkan penerapan SPBE pada Instansi Pusat dan Pemerintah Daerah dapat selaras dengan prinsip-prinsip Perpres SPBE.

Peraturan Menteri PANRB Nomor 59 Tahun 2020 mengatur mengenai tahap perencanaan, pelaksanaan, dan pelaporan atas pemantauan dan evaluasi penerapan SPBE yang telah dilakukan. Selain itu, Peraturan Menteri tersebut juga mengatur ruang lingkup pemantauan dan evaluasi SPBE yang mencakup domain kebijakan SPBE, tata kelola SPBE, manajemen SPBE, dan layanan SPBE yang dapat menggambarkan hasil penyelenggaraan SPBE baik pada Instansi Pusat maupun Pemerintah Daerah.

Hasil pelaksanaan pemantauan dan evaluasi SPBE diharapkan menjadi tolok ukur bagi Instansi Pusat dan Pemerintah Daerah untuk melakukan perbaikan pada aspek domain SPBE dimaksud, yang direpresentasikan berdasarkan nilai indeks SPBE. Tabel 1 di bawah ini menggambarkan perkembangan rata-rata capaian Indeks SPBE nasional dari tahun 2021-2023, yakni sejak dilaksanakannya Peraturan Menteri PANRB No. 59 Tahun 2020, sebagaimana tergambar dalam tabel di bawah ini.

3-

Tabel 1. Indeks SPBE Nasional (2021 – 2023)

Deskripsi 2021 2022 2023 Indeks SPBE Nasional 2,24 2,34 2,79 Indeks Domain Kebijakan 2,21 2,39 2,94 Indeks Domain Tata Kelola 1,89 1,85 2,29 Indeks Domain Manajemen 1,23 1,32 1,66 Indeks Domain Layanan 2,81 2,96 3,47 Jumlah IPPD Kategori “Baik” 159 237 388 Jumlah Responden (IPPD) 517 554 621

Berdasarkan capaian Indeks SPBE Nasional sebagaimana dimaksud secara umum menunjukkan peningkatan dari tahun ke tahun, namun dinamika perkembangan strategis penyelarasan implementasinya terdapat Indeks Domain yang masih di bawah target (<2,60) yaitu Indeks Domain Tata Kelola dan Indeks Domain Manajemen. Hal tersebut akan menjadi salah satu fokus yang dituangkan dalam Pedoman agar instrumen yang digunakan untuk melakukan pengukuran tingkat kematangan dapat dipahami dan diimplementasikan dengan komprehensif.

Selanjutnya, untuk dapat menyatukan pemahaman serta memberikan acuan baku, maka berdasarkan amanat Pasal 9 Peraturan Menteri PANRB No. 59 Tahun 2020 perlu dibentuk suatu pedoman teknis yang ditetapkan oleh Menteri PANRB untuk memudahkan setiap pihak yang terlibat dalam melaksanakan pemantauan dan evaluasi SPBE (dhi. Asesor Internal pada Instansi Pusat dan Pemerintah Daerah, Asesor Ekternal, serta Tim Pelaksanaan Pemantauan dan Evaluasi SPBE Kementerian PANRB). Pedoman dimaksud disusun untuk memudahkan pihak yang terlibat dalam mengimplementasikan SPBE beserta pengukuran tingkat kematangannya secara komprehensif. Untuk itu, agar pemantauan dan evaluasi SPBE dapat dilaksanakan dengan baik, maka diperlukan adanya penyempurnaan pada pedoman teknis pemantauan dan evaluasi SPBE.

jdih.menpan.go.id

4-

B. Maksud dan Tujuan

Pedoman Menteri ini dimaksudkan untuk memberi panduan bagi Asesor Internal Instansi Pusat dan Pemerintah Daerah, Asesor Eksternal, dan Tim Pelaksanaan Pemantauan dan Evaluasi SPBE Kementerian PANRB yang terlibat dalam penyelenggaraan pemantauan dan evaluasi SPBE. Pedoman Menteri ini bertujuan untuk:

a. memberikan panduan agar tercapai kesamaan pemahaman dan tindakan dalam proses penilaian pemantauan dan evaluasi SPBE;

b. memberikan petunjuk/tata cara dan kaidah dalam memberikan penjelasan pada proses penilaian pemantauan dan evaluasi SPBE; dan

c. menjamin kualitas dan memastikan tercapainya tujuan pelaksanaan pemantauan dan evaluasi SPBE secara sistematis.

C. Dasar Hukum

Peraturan Presiden Nomor 95 Tahun 2018 tentang Sistem Pemerintahan Berbasis Elektronik (Lembaran Negara Republik Indonesia Tahun 2018 Nomor 182);

Peraturan Presiden Nomor 95 Tahun 2019 tentang Satu Data Indonesia;

Peraturan Presiden Nomor 47 Tahun 2021 tentang Kementerian Pendayagunaan Aparatur Negara dan Reformasi Birokrasi (Lembaran Negara Republik Indonesia Tahun 2021 Nomor 126);

Peraturan Presiden Nomor 132 Tahun 2022 tentang Arsitektur Sistem Pemerintahan Berbasis Elektronik Nasional (Lembaran Negara Republik Indonesia Tahun 2022 Nomor 233);

Peraturan Presiden Nomor 82 Tahun 2023 tentang Percepatan Transformasi Digital dan Keterpaduan Layanan Digital Nasional (Lembaran Negara Republik Indonesia Nomor Tahun 2023 Nomor 159);

Peraturan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 59 Tahun 2020 tentang Pemantauan dan Evaluasi Sistem Pemerintahan Berbasis Elektronik (Berita Negara Tahun 2020 Nomor 994);

Peraturan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 3 Tahun 2023 tentang Perubahan Atas Peraturan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 25 Tahun 2020 tentang Road Map Reformasi Birokrasi 2020 – 2024;

Keputusan Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi Nomor 144 Tahun 2022 tentang Pembentukan Pedoman Menteri Pendayagunaan Aparatur Negara dan Reformasi Birokrasi.

D. Ruang Lingkup

Ruang lingkup Pedoman Menteri ini memuat pengaturan sebagai berikut:

a. ketentuan umum, mencakup gambaran umum instrumen yang digunakan dalam pelaksanaan pemantauan dan evaluasi SPBE;

b. ketentuan teknis instrumen pemantauan dan evaluasi SPBE;

c. mekanisme dan kaidah dalam melakukan penilaian pemantauan dan evaluasi SPBE; dan

d. etika Asesor, sebagai prinsip-prinsip yang perlu diperhatikan oleh setiap Asesor dalam melaksanakan tugas dan kewajibannya

BAB II INSTRUMEN PEMANTAUAN DAN EVALUASI SPBE

A. Ketentuan Umum

Kuesioner pemantauan dan evaluasi SPBE merupakan instrumen untuk mengumpulkan informasi penerapan SPBE di Instansi Pusat atau Pemerintah Daerah. Kuesioner pemantauan dan evaluasi SPBE disajikan dalam bentuk pertanyaan Tingkat Kematangan yang terdiri dari 47 (empat puluh tujuh) indikator. Instrumen tersebut selanjutnya akan digunakan sebagai alat penilaian bagi Asesor Internal dan/atau responden pada Instansi Pusat atau Pemerintah Daerah.

Dalam pelaksanaan pemantauan dan evaluasi SPBE, kuesioner dapat diakses melalui Aplikasi Pemantauan dan Evaluasi SPBE secara online. Alamat url serta cara penggunaan aplikasi tersebut akan disusun dan dipublikasikan oleh Asisten Deputi Perumusan Kebijakan dan Koordinasi Penerapan Sistem Pemerintahan Berbasis Elektronik melalui laman media resmi Kementerian PANRB ataupun media lainnya.

B. Pertanyaan Umum

Pertanyaan umum dalam hal ini disampaikan dalam bentuk pertanyaan terbuka, di mana pertanyaan umum ditujukan kepada responden dari Instansi Pusat dan Pemerintah Daerah (Tim Asesor Internal) untuk menuliskan jawaban atau melakukan entri data sesuai pertanyaan yang diakses melalui aplikasi pemnatauan dan evaluasi SPBE. Daftar pertanyaan umum diperlukan sebagai informasi pendukung dalam melakukan penilaian pemantauan dan evaluasi SPBE. Jumlah pertanyaan umum dapat bervariasi setiap tahunnya sesuai dengan perubahan isu-isu terkni terkait penerapan SPBE. Daftar pertanyaan umum setidaknya mencakup pertanyaan-pertanyaan berikut ini.

Berikan data/informasi mengenai layanan digital yang menggunakan pendekatan RB Tematik di Instansi Pusat atau Pemerintah Daerah

Berikan data/informasi mengenai rencana atau program integrasi yang telah dilakukan untuk mengintegrasikan beberapa aplikasi ke dalam satu portal layanan

Berikan data/informasi mengenai seluruh layanan utama dalam pelaksanaan tugas dan fungsi Instansi Pusat atau Pemerintah Daerah yang telah didukung SPBE

Berikan data/informasi mengenai rencana atau pemanfaatan Arsitektur SPBE dalam penyiapan layanan digital terpadu.

C. Pertanyaan Tingkat Kematangan

# Markdown Splitter

In [ ]:
from langchain_text_splitters import MarkdownHeaderTextSplitter # type: ignore
from langchain_text_splitters import RecursiveCharacterTextSplitter # type: ignore
# menggabungkan semua teks dari `spbe_md` menjadi satu string
markdown_text = "\n".join(doc.page_content for doc in spbe_md)

headers_to_split_on = [
    ("# SALINAN", "Title 1"),
    ("# BAB", "BAB"),
    ("## A", "SubBAB A"),
    ("## B", "SubBAB B"),
    ("## C", "SubBAB C"),
    ("## D", "SubBAB D"),
    ("## E", "SubBAB E"),
    ("## F", "SubBAB F"),
    ("## G", "SubBAB G"),
    ("# Indikator", "Indikator"),
    ("## Level", "Level"), 
]

# MD splits
markdown_splitter = MarkdownHeaderTextSplitter(
    headers_to_split_on=headers_to_split_on, strip_headers=False, return_each_line=True
)
md_header_splits = markdown_splitter.split_text(markdown_text)

In [ ]:
# Char-level splits
chunk_size = 1500
chunk_overlap = 100
text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=chunk_size, chunk_overlap=chunk_overlap
)

# Split
chunk_byMarkdown = text_splitter.split_documents(md_header_splits)
len(chunk_byMarkdown)

In [ ]:
for i, chunk in enumerate(chunk_byMarkdown):
    print(f"Chunk: {i+1}: \n{chunk.page_content}\n")

<!-- # Chunking the SPBE with Parent Document Retriever -->

<!-- Splitting Parent and Child Chunk -->

# Parent Document Splitter

In [7]:
from langchain_text_splitters import RecursiveCharacterTextSplitter # type: ignore

# Create a splitter for the parent documents
text_parent = RecursiveCharacterTextSplitter(chunk_size = 1500)

# Create a splitter for the child documents
# Note: child documents should be smaller than parent documents
text_child = RecursiveCharacterTextSplitter(chunk_size = 400)

<!-- Load Embedding Model -->

# Load Embedding Model

In [8]:
from langchain_ollama import OllamaEmbeddings # type: ignore

# load embedding model
embeddings = OllamaEmbeddings(
    model="nomic-embed-text:latest",
)

<!-- # Load Chroma as Vectorstore -->

# Initialize Vector Database ChromaDB

In [9]:
# Initialize a vector store to storing the chunks
from langchain_chroma import Chroma # type: ignore

parent_vstore = Chroma(
    collection_name="new2_spbe_parent_vector",
    embedding_function=embeddings,
    persist_directory ="./new2_chroma_spbe_parent_vector_db"
)

# initialize in-memory storage for the parent chunks
from langchain.storage import InMemoryStore # type: ignore
store_parent = InMemoryStore()

<!-- # Parent Document Retriever -->

# Initialize Parent Document Retriever

In [10]:
# Create a parent document retriever
from langchain.retrievers import ParentDocumentRetriever # type: ignore

parent_retriever = ParentDocumentRetriever(
    vectorstore=parent_vstore,
    docstore=store_parent, 
    child_splitter=text_child,
    parent_splitter=text_parent,
    search_kwargs={"k": 3}
)

In [11]:
# Cek jumlah dokumen
count = parent_vstore._collection.count()
print(f"Jumlah dokumen dalam ChromaDB: {count}")

Jumlah dokumen dalam ChromaDB: 2017

In [ ]:
# Hapus semua dokumen dari collection
if parent_vstore._collection:
    # Dapatkan semua IDs
    all_ids = parent_vstore._collection.get()['ids']
    if all_ids:
        parent_vstore._collection.delete(ids=all_ids)

# Cek jumlah dokumen yang tersimpan
print(f"Jumlah dokumen dalam ChromaDB: {parent_vstore._collection.count()}")

Jumlah dokumen dalam ChromaDB: 0

In [15]:
# add documents to vectorstore
parent_retriever.add_documents(md_header_splits)

In [16]:
# Cek jumlah dokumen yang tersimpan
print(f"Jumlah dokumen dalam ChromaDB: {parent_vstore._collection.count()}")

Jumlah dokumen dalam ChromaDB: 2017

<!-- # 4. Load LLM -->

# Initialize LLM from GroqCloud: Llama-3.3-70b

In [40]:
from langchain_groq import ChatGroq # type: ignore

# Verify API key is loaded
if not os.getenv("GROQ_API_KEY_RAGAS_REGIMR"):
    raise ValueError("GROQ_API_KEY not found in .env file")


model = ChatGroq(
    model_name="llama-3.3-70b-versatile",
    temperature=0,
    groq_api_key=os.getenv("GROQ_API_KEY_RAGAS_REGIMR"),
)

<!-- # 5. Routing and Prompt Template -->

# Prompt Routing

In [41]:
from langchain_core.prompts import PromptTemplate # type: ignore
from langchain_core.output_parsers import StrOutputParser # type: ignore

classification_template = PromptTemplate.from_template(
    """Kamu adalah ahli dalam menentukan jenis pertanyaan terkait SPBE.
    akan diberikan pertanyaan dari pengguna dibawah, tolong bantu klasifikasi apakah pertanyaan terkait SPBE `SPBE Umum` atau `SPBE Audit`.
    <jika pertanyaan adalah terkait hal umum yang ditanyakan terkait Sistem Pemerintahan Berbasis Elektronik (SPBE) seperti definisi, latar belakang, indeks tahun 2021-2023, dan keterangan alasan lainnya, maka klasifikasi pertanyaan sebagai 'SPBE Umum'>
    <jika pertanyaan sudah terkait studi kasus, memberikan permasalahan terkait penilaian indeks SPBE, kriteria, bukti dukung, indikator penilaian, tingkat kematangan berapa dan aspek lainnya yang kamu bisa tahu ini adalah pekerjaan audit dan juga jika opsi yang diminta untuk menentukan level itu termasuk kegiatan audit, maka klasifikasi pertanyaan sebagai 'SPBE Audit'>
    jangan berikan alasan apapun, cukup tolong klasifikasi saja jawabannya,
    - contoh pertanyaan:
    1. Apa saja domain yang ada di SPBE?
    - harapan jawaban klasifikasi: SPBE Umum
    2. Berapa indeks SPBE nasional tahun 2021-2023?
    - harapan jawaban klasifikasi: SPBE Umum
    3. Pada Indikator 32, Kab. Katingan melampirkan bukti dukung berupa screenshoot aplikasi SIPD, berapakah tingkat kematangan yang dapat diberikan dengan bukti dukung tersebut? Daftar Dokumen Pendukung: F2101-543-Indikator_32
    - harapan jawaban klasifikasi: SPBE Audit
    4. Penerapan Manajemen hanya dapat mencapai tingkat kematangan level 1 dikarenakan tidak?
    - harapan jawaban klasifikasi: SPBE Umum

    <pertanyaan>
    {question}
    </pertanyaan>

    Klasifikasi:"""
)

classification_chain = classification_template | model | StrOutputParser()

## Template Prompt

In [42]:
SPBE_UMUM_TEMPLATE = """Anda adalah asisten asesor SPBE yang detail, khususnya dalam memberikan informasi Sistem Pemerintahan Berbasis Elektronik (SPBE) Indonesia.

terkait Sistem Pemerintahan Berbasis Elektronik (SPBE). Didalamnya ada 4 Domain yang disingkat D (contoh: D1,D2,D3,D4), lalu ada 8 Aspek yang disingkat A (contoh: A2, A5) dan 47 Indikator yang disingkat ID (contoh: ID-3, ID-23). jadi struktur dari SPBE ada 3 unsur tadi domain, aspek, dan indikator, dan penilaian indikator ada kriteria level nya yaitu level 1-5,  dengan level 5 paling tinggi nya.
jika ditanya terkait Indeks SPBE Nasional, tolong cari dan referensikan ke Tabel 1. Indeks SPBE Nasional (2021 - 2023)

Ada 4 Domain utama SPBE:
1. Domain 1: Kebijakan
2. Domain 2: Tata Kelola
3. Domain 3: Manajemen
4. Domain 4: Layanan

Ada 8 Aspek utama SPBE:
1. Aspek 1: Kebijakan Tata Kelola SPBE
2. Aspek 2: Perencanaan Strategis SPBE
3. Aspek 3: Teknologi Informasi dan Komunikasi
4. Aspek 4: Penyelenggaraan SPBE
5. Aspek 5: Penerapan Manajemen SPBE
6. Aspek 6: Audit TIK
7. Aspek 7: Layanan Administrasi Pemerintahan
8. Aspek 8: Layanan Publik

Ada 47 Indikator utama SPBE:
1. Indikator 1-10 berada di Domain Kebijakan (bobot 13%)
2. Indikator 11-20 berada di Domain Tata Kelola (bobot 25%)
3. Indikator 21-31 berada di Domain Manajemen (bobot 16,5%)
4. Indikator 32-47 berada di Domain Layanan (bobot 45,5%)

Ada 5 Tingkat Kematangan Domain Kebijakan, Tata Kelola, dan Manajemen:
1. Rintisan
2. Terkelola
3. Terdefinisi
4. Terpadu dan Terukur
5. Optimum

Sedangkan untuk Domain Layanan:
1. Informasi
2. Interaksi
3. Transaksi
4. Kolaborasi
5. Optimum

## 🎯 Aturan Menjawab dan Tugas:
1. Menjawab pertanyaan umum tentang SPBE secara akurat.
2. Menunjukkan domain, aspek, dan indikator juga level terkait dengan pertanyaan pengguna berdasarkan pedoman SPBE jika pengguna menanyakan indikator/aspek/domain dan level nya juga memberikan alasan pemberian penilaian dari deskripsi ataupun kriteria, bukti lainnya.
3. Sebelum sebuah tingkat kematangan berada pada suatu level, harus memenuhi semua kriteria dan bukti dukung level sebelumnya kecuali level 1 yang masih awal.

## 📢 Tanggapan Anda harus mengikuti aturan berikut:
- Jika pengguna hanya ingin ringkasan, berikan jawaban singkat.
- jawab dengan konkrit tidak terlalu panjang dan jelas.
- Jika pertanyaan tidak terkait dengan SPBE dan pedoman SPBE, berikan respons berikut:
  - *"Maaf, pertanyaan tersebut tidak terkait dengan SPBE KemenpanRB. Saya hanya dapat memberikan jawaban berdasarkan konteks tersebut."
---

## 🔍 Konteks Riwayat Percakapan:
{chat_history}

## 🔍 Konteks yang diberikan dari dokumen:
{context}

## ❓ Pertanyaan pengguna:
{question}

## ✅ Jawaban Anda:
"""

SPBE_Audit_Template = """
Anda adalah asisten asesor SPBE yang detail, khususnya dalam membantu auditing Sistem Pemerintahan Berbasis Elektronik (SPBE) Indonesia.

terkait Sistem Pemerintahan Berbasis Elektronik (SPBE). Didalamnya ada 4 Domain yang disingkat D (contoh: D1,D2,D3,D4), lalu ada 8 Aspek yang disingkat A (contoh: A2, A5) dan 47 Indikator yang disingkat ID (contoh: ID-3, ID-23). jadi struktur dari SPBE ada 3 unsur tadi domain, aspek, dan indikator, dan penilaian indikator ada kriteria level nya yaitu level 1-5,  dengan level 5 paling tinggi nya.
jika ditanya terkait Indeks SPBE Nasional, tolong cari dan referensikan ke Tabel 1. Indeks SPBE Nasional (2021 - 2023)

Ada 4 Domain utama SPBE:
1. Domain 1: Kebijakan
2. Domain 2: Tata Kelola
3. Domain 3: Manajemen
4. Domain 4: Layanan

Ada 8 Aspek utama SPBE:
1. Aspek 1: Kebijakan Tata Kelola SPBE
2. Aspek 2: Perencanaan Strategis SPBE
3. Aspek 3: Teknologi Informasi dan Komunikasi
4. Aspek 4: Penyelenggaraan SPBE
5. Aspek 5: Penerapan Manajemen SPBE
6. Aspek 6: Audit TIK
7. Aspek 7: Layanan Administrasi Pemerintahan
8. Aspek 8: Layanan Publik

Ada 47 Indikator utama SPBE:
1. Indikator 1-10 berada di Domain Kebijakan (bobot 13%)
2. Indikator 11-20 berada di Domain Tata Kelola (bobot 25%)
3. Indikator 21-31 berada di Domain Manajemen (bobot 16,5%)
4. Indikator 32-47 berada di Domain Layanan (bobot 45,5%)

Ada 5 Tingkat Kematangan Domain Kebijakan, Tata Kelola, dan Manajemen:
1. Rintisan
2. Terkelola
3. Terdefinisi
4. Terpadu dan Terukur
5. Optimum

Sedangkan untuk Domain Layanan:
1. Informasi
2. Interaksi
3. Transaksi
4. Kolaborasi
5. Optimum

## 🎯 Aturan Menjawab dan Tugas:
1. Dalam memberikan penilaian level berapa sebuah indikator, maka pastikan memenuhi kriteria pemenuhan level dan kriteria bukti dukung, ini harus ada jika melakukan audit, kalau tidak ada maka mintakan kepada pengguna hal tersebut.
2. Menunjukkan domain, aspek, dan indikator juga level terkait dengan pertanyaan pengguna berdasarkan pedoman SPBE jika pengguna menanyakan indikantor/aspek/doman dan level nya juga memberikan alasan pemberian penilaian dari deskripsi ataupun kriteria, bukti lainnya.
3. Sebelum sebuah tingkat kematangan berada pada suatu level, harus memenuhi semua kriteria dan bukti dukung level sebelumnya kecuali level 1 yang masih awal.
4. Kamu akan diberikan konteks dibawah, jadi pastikan hal yang dibutuhkan untuk penilaian tersedia, jangan menjawab jika konteks tidak tersedia

## 📢 Tanggapan Anda harus mengikuti aturan berikut:
- jawab dengan konkrit tidak terlalu panjang dan jelas.
- Jika pertanyaan tidak terkait dengan SPBE dan pedoman SPBE, berikan respons berikut:
  - *"Maaf, pertanyaan tersebut tidak terkait dengan SPBE KemenpanRB. Saya hanya dapat memberikan jawaban berdasarkan konteks tersebut."
---
Berikut contoh format jawaban yang harus kamu lakukan:
<contoh format jawaban>
Berdasarkan pedoman pemantauan dan evaluasi SPBE.....dengan diberikannya informasi tahapan, kriteria pemenuhan level dan bukti dukung maka indeks SPBE diberikan: 

{{ 
  "Penilaian": {{
    "Level": 5,
    "Indikator": 3,
    "Aspek": 2,
    "Domain": 1
  }}
}}

alasan penilaian diatas karena.....level.....indikator....aspek....domain...sesuai standard dari pedoman evaluasi SPBE.
</contoh format jawaban>
yang titik diatas kamu harus isi alasannya, dan sesuai format

## 🔍 Konteks Riwayat Percakapan:
{chat_history}

## 🔍 Konteks yang diberikan dari dokumen:
{context}

## ❓ Pertanyaan pengguna:
{question}

## ✅ Jawaban Anda:
"""

In [43]:
from langchain_core.runnables import RunnableLambda # type: ignore

def get_classification_prompt(input_query):
    return classification_chain.invoke({"question": input_query["question"]}).strip()

def prompt_router(input_query):
    classification_query = classification_chain.invoke({"question": input_query["question"]}).strip()

    if classification_query == "SPBE Umum":
        prompt = PromptTemplate(template=SPBE_UMUM_TEMPLATE, input_variables=["chat_history", "context", "question"])
    elif classification_query == "SPBE Audit":
        prompt = PromptTemplate(template=SPBE_Audit_Template, input_variables=["chat_history", "context", "question"])
    else:
        print("Unexpected classification: ", classification_query)
        
    return prompt

<!-- # Function Invoke -->

In [ ]:
from langchain.memory import ConversationBufferMemory # type: ignore
from langchain.chains import ConversationalRetrievalChain # type: ignore
# Create memory with explicit chat history
memory2 = ConversationBufferMemory(
    memory_key="chat_history",
    return_messages=True,
    output_key='answer'
)

# Chain Parent Retriever

In [ ]:
# from langchain.chains import ConversationalRetrievalChain

# # Create chain with explicit source document handling
# parent_chain = ConversationalRetrievalChain.from_llm(
#     llm=model,
#     retriever=parent_retriever,
#     memory=memory,
#     return_source_documents=True,
#     combine_docs_chain_kwargs={
#         "prompt": prompt,
#         "document_variable_name": "context"
#     },
#     verbose=True  # Enable verbose mode for debugging
# )

# chat_history = []
# result = parent_chain.invoke({
#     "chat_history": chat_history,
#     "question": question
# })
# response = result["answer"]
# print(response)
# source_documents = result.get("source_documents", [])

In [ ]:
# pprint_docs(parent_retriever.invoke(questions[0]))

# MultiQuery Combine to Parent Document Retriever

In [45]:
from langchain.retrievers.multi_query import MultiQueryRetriever # type: ignore

multi_parent_retriever = MultiQueryRetriever.from_llm(
    retriever=parent_retriever, llm=model
)

In [46]:
# Set logging for the queries
import logging

logging.basicConfig()
logging.getLogger("langchain.retrievers.multi_query").setLevel(logging.INFO)

question_multi_query = """Dalam penerapan Manajemen Risiko SPBE, masing-masing IPPD (Instansi Pusat dan Pemerintah Daerah) dapat mengacu pada Pedoman Manajemen Risiko SPBE yang ditetapkan dalam kebijakan:"""

unique_docs = multi_parent_retriever.invoke(question_multi_query)
len(unique_docs)

# Getting Classification Prompt
classification_prompt_result = get_classification_prompt({"question": question_multi_query})
print(f"🔍 Hasil Klasifikasi: {classification_prompt_result}")

INFO:langchain.retrievers.multi_query:Generated queries: ['Berikut adalah tiga versi alternatif dari pertanyaan asli untuk membantu mengatasi keterbatasan pencarian kesamaan berbasis jarak:', 'Apa pedoman yang digunakan oleh Instansi Pusat dan Pemerintah Daerah dalam menerapkan Manajemen Risiko SPBE?', 'Dalam konteks Manajemen Risiko SPBE, apa kebijakan yang menjadi acuan bagi IPPD (Instansi Pusat dan Pemerintah Daerah) untuk mengelola risiko?', 'Bagaimana IPPD (Instansi Pusat dan Pemerintah Daerah) dapat menerapkan Manajemen Risiko SPBE sesuai dengan pedoman yang telah ditetapkan dalam kebijakan?']

🔍 Hasil Klasifikasi: SPBE Umum

In [47]:
def run_multi_parent_chain(question):
    """
    Function to run multi-parent chain with error handling
    """
    try:
        prompt = prompt_router({"question": question})
        multi_parent_chain = ConversationalRetrievalChain.from_llm(
            llm=model,
            retriever=multi_parent_retriever,
            return_source_documents=True,
            combine_docs_chain_kwargs={
                "prompt": prompt,
                "document_variable_name": "context"
            },
            verbose=True  # Enable verbose mode for debugging
        )

        chat_history10 = []
        result10 = multi_parent_chain.invoke({
            "chat_history": chat_history10,
            "question": question
        })
        print(result10["answer"])
        return result10
        
    except Exception as e:
        print(f"Error occurred: {str(e)}")
        return None

# Call the function to execute and display results
# run_multi_parent_chain(question_multi_query)

In [ ]:
# chat_history10 = []
# result10 = multi_parent_chain.invoke({
#     "chat_history": chat_history10,
#     "question": question_multi_query
# })
# response10 = result10["answer"]
# print(response10)
# # source_documents = result.get("source_documents", [])

# Evaluasi RAG with RAGAS

In [48]:
def prepare_ragas_data(result, references=None):
    """
    Menyiapkan data untuk evaluasi RAGAS dari result function run_multi_parent_chain
    """
    if result is None:
        return None 
    
    # Mengakses answer dan context
    generated_answer = result["answer"]
    source_documents = result.get("source_documents", [])
    
    # Menggabungkan context dari semua source documents
    retrieved_contexts = "\n\n".join([doc.page_content for doc in source_documents])
    
    return {
        "response": generated_answer,
        "retrieved_contexts": retrieved_contexts,
        "reference": references,
        "source_documents": source_documents
    }

In [49]:
import time

def evaluate_with_ragas(questions, references=None):
    """
    Evaluasi menggunakan RAGAS dengan function run_multi_parent_chain yang sudah ada
    """
    ragas_dataset = []
    
    for i, question in enumerate(questions):
        print(f"Processing question {i+1}/{len(questions)}: {question[:50]}...")
        

        result = run_multi_parent_chain(question)
        
        if result:
            # Mendapatkan ground truth jika ada
            reference = references[i] if references and i < len(references) else None
            
            # Menyiapkan data RAGAS
            ragas_data = prepare_ragas_data(result, reference)
            
            if ragas_data:
                # Menambahkan question ke data
                ragas_data["user_input"] = question
                ragas_dataset.append(ragas_data)
                print(f"✅ Question {i+1} processed successfully")
            else:
                print(f"❌ Failed to prepare RAGAS data for question {i+1}")
        else:
            print(f"❌ Failed to process question {i+1}")

        # Jeda
        print("⏳ Menunggu 30 detik...")
        time.sleep(30)
    
    return ragas_dataset

In [50]:
# Contoh penggunaan
questions_for_evaluation = [
    """Dalam penerapan Manajemen Risiko SPBE, masing-masing IPPD (Instansi Pusat dan Pemerintah Daerah) dapat mengacu pada Pedoman Manajemen Risiko SPBE yang ditetapkan dalam kebijakan:
""",
    """Jika "Rencana dan Anggaran SPBE Instansi Pusat Pemerintah Daerah telah terpadu dan dapat dikendalikan oleh unit kerja/perangkat daerah yang menjalankan fungsi perencanaan dan penganggaran dan telah direviu serta dievaluasi secara periodik:" Maka dapat diberikan level...
    """,
    "Berapa nilai indeks domain yang masih dibawah target pada tahun 2021-2023?",
    """Sebuah IPPD melampirkan Peta Rencana SPBE yang telah didokumentasikan secara formal, dan mengklaim memiliki dokumen Peta Rencana SPBE yang telah mengatur seluruh muatan Peta Rencana SPBE Instansi Pusat Pemerintah Daerah. Dokumen Peta Rencana yang diunggah berisikan muatan Peta Rencana secara lengkap antara lain Tata Kelola SPBE, Manajemen SPBE, Layanan SPBE, Arsitektur SPBE, Aplikasi SPBE, Keamanan SPBE dan Audit TIK. Maka level yang pantas diberikan adalah...
""",
    """Dibawah ini merupakan domain-domain dari Arsitektur SPBE berdasarkan Perpres SPBE, kecuali (pilih salah satu):

- domain arsitektur Proses Bisnis
- domain arsitektur Manajemen SPBE 
- domain arsitektur Infrastruktur SPBE
- domain arsitektur Aplikasi SPBE
- domain arsitektur Keamanan SPBE
- domain arsitektur Layanan SPBE
"""
]

references = [
    """PermenPANRB No. 5 Tahun 2020 memberikan pedoman umum bagi Instansi Pusat dan Pemerintah Daerah dalam melaksanakan SPBE, termasuk penerapan Manajemen Risiko SPBE
    """,
    """Berdasarkan pedoman pemantauan dan evaluasi SPBE, dengan diberikannya informasi kriteria-kriteria, maka indeks SPBE yang diberikan: 
 
Penilaian: 
Level: 4,
Indikator: 13,
Aspek: 2,
Domain: 2

Alasan penilaian diatas karena Rencana dan Anggaran SPBE Instansi Pusat/Pemerintah Daerah telah terpadu dan dapat dikendalikan oleh unit kerja/perangkat daerah yang menjalankan fungsi perencanaan dan penganggaran dan telah direviu serta dievaluasi secara periodik, sehingga sesuai dengan kriteria Level 4 pada Domain Tata Kelola, Aspek Perencanaan Strategis SPBE, dan Indikator 13 tentang tingkat kematangan keterpaduan rencana dan anggaran SPBE.
""",
    """Nilai indeks domain yang masih di bawah target (<2,60) pada tahun 2021-2023 adalah:

1. Indeks Domain Tata Kelola: 
   - Tahun 2021: 1,89
   - Tahun 2022: 1,85
   - Tahun 2023: 2,29

2. Indeks Domain Manajemen: 
   - Tahun 2021: 1,23
   - Tahun 2022: 1,32
   - Tahun 2023: 1,66
   """,
    """Berdasarkan pedoman pemantauan dan evaluasi SPBE, dengan diberikannya informasi kriteria-kriteria, maka indeks SPBE yang diberikan: 
 
Penilaian: 
Level: 3,
Indikator: 12,
Aspek: 2,
Domain: 2

Alasan penilaian diatas karena dokumen Peta Rencana SPBE telah mengatur seluruh muatan Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah secara lengkap (Tata Kelola SPBE, Manajemen SPBE, Layanan SPBE, Infrastruktur SPBE, Aplikasi SPBE, Keamanan SPBE, Audit Teknologi SPBE dan Audit TIK) dan dokumen Peta Rencana SPBE telah didokumentasikan secara formal, sehingga sesuai dengan kriteria Level 3 pada Domain Tata Kelola, Aspek Perencanaan Strategis SPBE, dan Indikator 12 tentang Tingkat Kematangan Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah. Namun, perlu diperhatikan bahwa untuk mencapai Level 4, IPPD harus memenuhi kriteria tambahan, yaitu dokumen Peta Rencana SPBE telah diterapkan secara konsisten melalui rencana kerja dan anggaran 3 (tiga) tahun terakhir, dan dokumen Peta Rencana SPBE telah dilakukan reviu dan evaluasi secara periodik.
""",
    "Domain Arsitektur Manajemen SPBE tidak termasuk dalam daftar domain arsitektur SPBE yang ditetapkan dalam Perpres SPBE. Domain Manajemen SPBE sebenarnya merupakan salah satu aspek dalam Sistem Pemerintahan Berbasis Elektronik (SPBE), bukan domain arsitektur SPBE."
]

# Menjalankan evaluasi
ragas_dataset = evaluate_with_ragas(questions_for_evaluation, references)

# Menampilkan hasil
print(f"\n📊 Dataset RAGAS berhasil disiapkan dengan {len(ragas_dataset)} sampel")
for i, data in enumerate(ragas_dataset):
    print(f"\n--- Sampel {i+1} ---")
    print(f"Question: {data['user_input']}")
    print(f"Context Length: {len(data['retrieved_contexts'])} characters")
    print(f"Response: {data['response'][:100]}...")
    if data['reference']:
        print(f"Reference: {data['reference'][:100]}...")

Processing question 1/5: Dalam penerapan Manajemen Risiko SPBE, masing-masi...

INFO:langchain.retrievers.multi_query:Generated queries: ['Apa saja pedoman manajemen risiko SPBE yang perlu diikuti oleh Instansi Pusat dan Pemerintah Daerah dalam penerapan Manajemen Risiko SPBE?', 'Dalam konteks kebijakan, bagaimana pedoman manajemen risiko SPBE dapat membantu IPPD (Instansi Pusat dan Pemerintah Daerah) mengelola risiko yang terkait dengan Sistem Pengelolaan Barang Milik Negara atau Daerah?', 'Bagaimana IPPD (Instansi Pusat dan Pemerintah Daerah) dapat menerapkan pedoman manajemen risiko SPBE yang efektif untuk mengoptimalkan pengelolaan barang milik negara atau daerah dan meminimalkan risiko yang terkait?']

> Entering new StuffDocumentsChain chain...


> Entering new LLMChain chain...
Prompt after formatting:
Anda adalah asisten asesor SPBE yang detail, khususnya dalam memberikan informasi Sistem Pemerintahan Berbasis Elektronik (SPBE) Indonesia.

terkait Sistem Pemerintahan Berbasis Elektronik (SPBE). Didalamnya ada 4 Domain yang disingkat D (contoh: D1,D2,D3,D4), lalu ada 8 Aspek yang disingkat A (contoh: A2, A5) dan 47 Indikator yang disingkat ID (contoh: ID-3, ID-23). jadi struktur dari SPBE ada 3 unsur tadi domain, aspek, dan indikator, dan penilaian indikator ada kriteria level nya yaitu level 1-5,  dengan level 5 paling tinggi nya.
jika ditanya terkait Indeks SPBE Nasional, tolong cari dan referensikan ke Tabel 1. Indeks SPBE Nasional (2021 - 2023)

Ada 4 Domain utama SPBE:
1. Domain 1: Kebijakan
2. Domain 2: Tata Kelola
3. Domain 3: Manajemen
4. Domain 4: Layanan

Ada 8 Aspek utama SPBE:
1. Aspek 1: Kebijakan Tata Kelola SPBE
2. Aspek 2: Perencanaan Strategis SPBE
3. Aspek 3: Teknologi Informasi dan Komunikasi
4. Aspek 4: Penyelenggaraan SPBE
5. Aspek 5: Penerapan Manajemen SPBE
6. Aspek 6: Audit TIK
7. Aspek 7: Layanan Administrasi Pemerintahan
8. Aspek 8: Layanan Publik

Ada 47 Indikator utama SPBE:
1. Indikator 1-10 berada di Domain Kebijakan (bobot 13%)
2. Indikator 11-20 berada di Domain Tata Kelola (bobot 25%)
3. Indikator 21-31 berada di Domain Manajemen (bobot 16,5%)
4. Indikator 32-47 berada di Domain Layanan (bobot 45,5%)

Ada 5 Tingkat Kematangan Domain Kebijakan, Tata Kelola, dan Manajemen:
1. Rintisan
2. Terkelola
3. Terdefinisi
4. Terpadu dan Terukur
5. Optimum

Sedangkan untuk Domain Layanan:
1. Informasi
2. Interaksi
3. Transaksi
4. Kolaborasi
5. Optimum

## 🎯 Aturan Menjawab dan Tugas:
1. Menjawab pertanyaan umum tentang SPBE secara akurat.
2. Menunjukkan domain, aspek, dan indikator juga level terkait dengan pertanyaan pengguna berdasarkan pedoman SPBE jika pengguna menanyakan indikator/aspek/domain dan level nya juga memberikan alasan pemberian penilaian dari deskripsi ataupun kriteria, bukti lainnya.
3. Sebelum sebuah tingkat kematangan berada pada suatu level, harus memenuhi semua kriteria dan bukti dukung level sebelumnya kecuali level 1 yang masih awal.

## 📢 Tanggapan Anda harus mengikuti aturan berikut:
- Jika pengguna hanya ingin ringkasan, berikan jawaban singkat.
- jawab dengan konkrit tidak terlalu panjang dan jelas.
- Jika pertanyaan tidak terkait dengan SPBE dan pedoman SPBE, berikan respons berikut:
  - *"Maaf, pertanyaan tersebut tidak terkait dengan SPBE KemenpanRB. Saya hanya dapat memberikan jawaban berdasarkan konteks tersebut."
---

## 🔍 Konteks Riwayat Percakapan:


## 🔍 Konteks yang diberikan dari dokumen:
INDIKATOR 21
Domain Aspek Ind Kuesioner D3 A5 ID-21 Tingkat Kematangan Penerapan Manajemen Risiko SPBE. Deskripsi Indikator: a. Manajemen Risiko SPBE adalah pendekatan sistematis yang meliputi proses, pengukuran, struktur, dan budaya untuk menentukan tindakan terbaik terkait Risiko SPBE; b. Risiko SPBE adalah peluang terjadinya suatu peristiwa yang akan mempengaruhi keberhasilan terhadap pencapaian tujuan penerapan SPBE; c. Manajemen Risiko bertujuan untuk menjamin keberlangsungan SPBE dengan meminimalkan dampak risiko dalam SPBE; d. Instansi Pusat dan Pemerintah Daerah menerapkan manajemen risiko SPBE berdasarkan pedoman Manajemen Risiko SPBE. Ketentuan Penilaian: Penilaian dilakukan terhadap bukti dukung penerapan manajemen risiko Instansi Pusat/Pemerintah Daerah yang memenuhi kriteria ruang lingkup, serta terdokumentasi secara formal. Contoh Bukti Dukung: Bukti dukung tingkat kematangan dilampirkan berupa dokumentasi pemenuhan sesuai huruf d. Data Pendukung dapat disampaikan lebih dari 1 (satu) jenis dokumen. Level 1 Kriteria Level Kegiatan Manajemen Risiko SPBE belum atau telah diterapkan. Kondisi: Kegiatan Manajemen Risiko SPBE diterapkan tanpa program kegiatan yang terarah dan terencana. Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah belum atau sudah menerapkan kegiatan Manajemen Risiko SPBE tanpa program kegiatan yang terarah dan terencana. Kriteria Bukti Dukung Draf/rancangan penerapan Manajemen Risiko SPBE, notulensi/catatan penyusunan rancangan penerapan

penerapannya dibuktikan dengan data dukung 21.b. Matrik-Manrisk-SPBE.pdf yaitu form dan matriks hasil pengisian manajemen risiko SPBE pada Pemprov DKI Jakarta (FAKTA). Penerapan manajemen risiko SPBE sudah dilakukan oleh unit kerja/OPD terkait sesuai ketentuan PermenPANRB no.5/2020 namun belum ditetapkan (ANALISIS). | | 4 | Kriteria tingkat 3 telah terpenuhi dan kebijakan strategis Manajemen Risiko SPBE telah ditetapkan oleh Komite Manajemen Risiko SPBE atau Tim KoordinasiSPBE Instansi Pusat/Pemerintah Daerah dan diterapkan ke seluruh unit kerja/perangkat daerah di Instansi Pusat/Pemerintah Daerah. Selain itu, penerapan Manajemen Risiko SPBE telah di dievaluasi secara periodik. | Penerapan Manajemen Risiko SPBE telah dilakukan sesuai ketentuan program strategis kebijakan tata kelola SPBE 21.a. Pergub-Tatakelola-SPBE.pdf pada Pasal 12 Halaman 23 yang kemudian dokumentasi penerapannya telah ditetapkan oleh Koordinator Tim Koordinasi SPBE sesuai data dukung 21.b.SK-Manrisk-SPBE.pdf yang kemudian pelaksanaannya melibatkan seluruh unit kerja/OPD, kemudian sesuai data dukung 21.c. Reviu-Manrisk_SPBE.pdf halaman 30 sudah dilakukan reviu/evaluasi terhadap perkembangan progres tindak lanjut mitigasi risiko/rekomendasi penanganan risiko yang tidak tercapai (FAKTA). Dari data dukung yang disampaikan menggambarkan Penerapan Manajemen SPBE sudah dilakukan secara terprogram dan menyeluruh terhadap seluruh unit kerja/OPD, serta dilakukan reviu/evaluasi (ANALISIS). | | 5 | Kriteria tingkat

Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah menerapkan Manajemen Risiko SPBE sesuai dengan pedoman Manajemen Risiko SPBE yang berlaku.
Kriteria Bukti Dukung Konteks penerapan Manajemen Risiko SPBE yang menguraikan seluruh pemenuhannya sesuai dengan pedoman/standar Manajemen Risiko yang telah ditentukan/ditetapkan yang terdokumentasi secara formal dan dilengkapi komitmen berupa pakta integritas.
Level 4 Kriteria Level Kriteria tingkat 3 telah terpenuhi dan kebijakan strategis Manajemen Risiko SPBE telah ditetapkan oleh Komite Manajemen Risiko SPBE atau Tim Koordinasi SPBE Instansi Pusat/Pemerintah
jdih.menpan.go.id
88-

Kondisi: Manajemen Pengetahuan SPBE telah dilaksanakan tanpa pedoman di Instansi Pusat/Pemerintah Daerah. Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah sudah menerapkan kegiatan Manajemen Pengetahuan SPBE sesuai dan selaras dengan program kegiatan yang tercantum dalam Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah, namun pelaksanaannya belum mengacu pada pedoman yang berlaku. Kriteria Bukti Dukung Perencanaan program kerja/aktivitas kegiatan penerapan Manajemen Pengetahuan SPBE tertuang di dalam dokumen Peta Rencana SPBE yang masih berlaku dan terdokumentasi secara formal, namun penerapannya belum mengacu pada pedoman/standar Manajemen Pengetahuan yang telah ditentukan/ditetapkan. Level 3 Kriteria Level Kriteria tingkat 2 telah terpenuhi, Manajemen Pengetahuan SPBE dilaksanakan dengan mengacu pada pedoman di Instansi Pusat/Pemerintah Daerah dan Manajemen Pengetahuan SPBE diterapkan menggunakan sistem aplikasi manajemen pengetahuan. Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah menerapkan Manajemen Pengetahuan SPBE dan telah tersedia pedoman pelaksanaan manajemen pengetahuan yang disusun sesuai dengan pedoman manajemen pengetahuan SPBE di tingkat nasional, di mana struktur pengelola serta penugasan diuraikan dengan jelas. Selain itu, manajemen pengetahuan SPBE diterapkan menggunakan sistem aplikasi manajemen pengetahuan. Kriteria Bukti Dukung 1. Dokumen pedoman pelaksanaan Manajemen Pengetahuan SPBE Instansi Pusat/Pemerintah Daerah yang

## ❓ Pertanyaan pengguna:
Dalam penerapan Manajemen Risiko SPBE, masing-masing IPPD (Instansi Pusat dan Pemerintah Daerah) dapat mengacu pada Pedoman Manajemen Risiko SPBE yang ditetapkan dalam kebijakan:


## ✅ Jawaban Anda:


> Finished chain.

> Finished chain.
Dalam penerapan Manajemen Risiko SPBE, masing-masing IPPD (Instansi Pusat dan Pemerintah Daerah) dapat mengacu pada Pedoman Manajemen Risiko SPBE yang ditetapkan dalam PermenPANRB No. 5/2020.
✅ Question 1 processed successfully
⏳ Menunggu 30 detik...
Processing question 2/5: Jika "Rencana dan Anggaran SPBE Instansi Pusat Pem...

INFO:langchain.retrievers.multi_query:Generated queries: ['Berikut adalah tiga versi alternatif dari pertanyaan asli untuk membantu mengatasi keterbatasan pencarian kesamaan berbasis jarak:', 'Apa tingkat integrasi rencana dan anggaran SPBE di instansi pemerintah daerah yang telah mencapai tingkat kematangan dalam pengelolaan perencanaan dan penganggaran, serta melakukan review dan evaluasi secara berkala?', 'Jika suatu instansi pemerintah daerah telah berhasil mengintegrasikan rencana dan anggaran SPBE, serta melakukan pengendalian dan evaluasi secara terstruktur oleh unit kerja yang relevan, maka apa level kematangan yang dapat diberikan?', 'Bagaimana tingkat kematangan suatu instansi pemerintah daerah dalam mengelola rencana dan anggaran SPBE yang telah terintegrasi, dapat dikendalikan oleh unit kerja yang tepat, dan telah melalui proses review serta evaluasi secara periodik, sehingga layak diberikan level tertentu?']

> Entering new StuffDocumentsChain chain...


> Entering new LLMChain chain...
Prompt after formatting:

Anda adalah asisten asesor SPBE yang detail, khususnya dalam membantu auditing Sistem Pemerintahan Berbasis Elektronik (SPBE) Indonesia.

terkait Sistem Pemerintahan Berbasis Elektronik (SPBE). Didalamnya ada 4 Domain yang disingkat D (contoh: D1,D2,D3,D4), lalu ada 8 Aspek yang disingkat A (contoh: A2, A5) dan 47 Indikator yang disingkat ID (contoh: ID-3, ID-23). jadi struktur dari SPBE ada 3 unsur tadi domain, aspek, dan indikator, dan penilaian indikator ada kriteria level nya yaitu level 1-5,  dengan level 5 paling tinggi nya.
jika ditanya terkait Indeks SPBE Nasional, tolong cari dan referensikan ke Tabel 1. Indeks SPBE Nasional (2021 - 2023)

Ada 4 Domain utama SPBE:
1. Domain 1: Kebijakan
2. Domain 2: Tata Kelola
3. Domain 3: Manajemen
4. Domain 4: Layanan

Ada 8 Aspek utama SPBE:
1. Aspek 1: Kebijakan Tata Kelola SPBE
2. Aspek 2: Perencanaan Strategis SPBE
3. Aspek 3: Teknologi Informasi dan Komunikasi
4. Aspek 4: Penyelenggaraan SPBE
5. Aspek 5: Penerapan Manajemen SPBE
6. Aspek 6: Audit TIK
7. Aspek 7: Layanan Administrasi Pemerintahan
8. Aspek 8: Layanan Publik

Ada 47 Indikator utama SPBE:
1. Indikator 1-10 berada di Domain Kebijakan (bobot 13%)
2. Indikator 11-20 berada di Domain Tata Kelola (bobot 25%)
3. Indikator 21-31 berada di Domain Manajemen (bobot 16,5%)
4. Indikator 32-47 berada di Domain Layanan (bobot 45,5%)

Ada 5 Tingkat Kematangan Domain Kebijakan, Tata Kelola, dan Manajemen:
1. Rintisan
2. Terkelola
3. Terdefinisi
4. Terpadu dan Terukur
5. Optimum

Sedangkan untuk Domain Layanan:
1. Informasi
2. Interaksi
3. Transaksi
4. Kolaborasi
5. Optimum

## 🎯 Aturan Menjawab dan Tugas:
1. Dalam memberikan penilaian level berapa sebuah indikator, maka pastikan memenuhi kriteria pemenuhan level dan kriteria bukti dukung, ini harus ada jika melakukan audit, kalau tidak ada maka mintakan kepada pengguna hal tersebut.
2. Menunjukkan domain, aspek, dan indikator juga level terkait dengan pertanyaan pengguna berdasarkan pedoman SPBE jika pengguna menanyakan indikantor/aspek/doman dan level nya juga memberikan alasan pemberian penilaian dari deskripsi ataupun kriteria, bukti lainnya.
3. Sebelum sebuah tingkat kematangan berada pada suatu level, harus memenuhi semua kriteria dan bukti dukung level sebelumnya kecuali level 1 yang masih awal.
4. Kamu akan diberikan konteks dibawah, jadi pastikan hal yang dibutuhkan untuk penilaian tersedia, jangan menjawab jika konteks tidak tersedia

## 📢 Tanggapan Anda harus mengikuti aturan berikut:
- jawab dengan konkrit tidak terlalu panjang dan jelas.
- Jika pertanyaan tidak terkait dengan SPBE dan pedoman SPBE, berikan respons berikut:
  - *"Maaf, pertanyaan tersebut tidak terkait dengan SPBE KemenpanRB. Saya hanya dapat memberikan jawaban berdasarkan konteks tersebut."
---
Berikut contoh format jawaban yang harus kamu lakukan:
<contoh format jawaban>
Berdasarkan pedoman pemantauan dan evaluasi SPBE.....dengan diberikannya informasi tahapan, kriteria pemenuhan level dan bukti dukung maka indeks SPBE diberikan:

{
  "Penilaian": {
    "Level": 5,
    "Indikator": 3,
    "Aspek": 2,
    "Domain": 1
  }
}

alasan penilaian diatas karena.....level.....indikator....aspek....domain...sesuai standard dari pedoman evaluasi SPBE.
</contoh format jawaban>
yang titik diatas kamu harus isi alasannya, dan sesuai format

## 🔍 Konteks Riwayat Percakapan:


## 🔍 Konteks yang diberikan dari dokumen:
d. Tidak menerima gratifikasi terkait dengan penugasan sebagai asesor dalam bentuk apapun.
234-
B.2. Untuk menerapkan prinsip Objektivitas, Asesor diharapkan:
a. Tidak berpartisipasi dalam kegiatan atau hubungan apapun yang dapat menimbulkan konflik dengan kepentingan penugasannya sebagai asesor, atau yang dapat menimbulkan prasangka, atau yang meragukan kemampuannya untuk dapat melaksanakan tugas dan memenuhi tanggung jawab profesinya secara objektif; b. Tidak menerima sesuatu dalam bentuk apapun yang dapat mengganggu atau patut diduga mengganggu pertimbangan profesionalnya; dan c. Mengungkapkan semua fakta material yang diketahui, yaitu fakta yang jika tidak diungkapkan dapat mengubah atau mempengaruhi penilaian dalam pelaksanaan pemantauan dan evaluasi SPBE.
B.3. Untuk menerapkan prinsip Kerahasiaan, Asesor diharapkan:
a. Berhati-hati dalam penggunaan dan pelindungan informasi yang diperoleh dalam tugasnya; dan b. Tidak menggunakan informasi untuk keuntungan pribadi atau dengan cara apapun yang akan bertentangan dengan ketentuan atau merugikan tujuan pelaksanaan pemantauan dan evaluasi SPBE yang sah dan etis.
B.4. Untuk menerapkan prinsip Kompetensi, Asesor diharapkan:
a. Memberikan kontribusi pelaksanaan tugas sesuai dengan pengetahuan, keahlian dan keterampilan, serta pengalaman yang diperlukan; dan b. Melakukan kegiatan pemantauan dan evaluasi SPBE sesuai dengan ketentuan yang berlaku.

Namun disisi lain, Badan xxx masih terdapat beberapa kelemahan, khususnya pada aspek Layanan Publik. Layanan Publik memang sudah direncanakan pada Arsitektur SPBE dan Peta Rencana SPBE dan berdasarkan penerapan Rencana dan Anggaran SPBE sudah terakomodasi, namun pada penerapannya, kapabilitas fungsi teknis dari layanan tersebut masih rendah, dimana masih banyak aplikasi publik yang dibangun secara sendiri-sendiri, sehingga tidak memanfaatkan potensi transaksi dan integrasi terhadap layanan SPBE lainnya. Hal ini menyebabkan Layanan Publik yang diberikan tidak efektif dan optimal pemanfaatannya
Pada Aspek Kebijakan Layanan yang masih bersifat mengatur secara internal perlu ditingkatkan untuk mengakomodasi arah kolaborasi dan integrasi serta dapat ditingkatkan sesuai kebutuhan Badan xxx. Aspek Layanan Publik yang tingkat kematangannya masih rendah, agar dapat menggunakan aplikasi umum berbagi pakai yang telah tetapkan secara nasional, atau melakukan replikasi dari layanan-layanan publik sejenis yang dibangun oleh Instansi lainnya. Diharapkan dapat melakukan inisiatif penerapan Manajemen SPBE sesuai dengan Peraturan yang berlaku, sehingga pada pelaksanaan evaluasi SPBE selanjutnya sudah dapat memenuhi indikator dan kriteria penilaian sesuai target
G. Tata Cara dan Kaidah Penyusunan Hasil Reviu Bagi Tim Reviu.

Catatan Penilaian Visit
Klarifikasi tidak dilakukan terhadap Indikator <<No, dan Subste Berdasarkan hasil verifikasi <
Gambar 4. Penilaian Visitasi Pada Aplikasi
Asesor Eksternal dapat melakukan klarifikasi, verifikasi, dan validasi kepada Asesor Internal terhadap indikator yang memerlukan perincian dan data dukung tambahan. Dalam memberikan penjelasan dalam penilaian, Asesor Eksternal agar mengacu pada kaidah berikut ini, sehingga uraian hasil penilaian eksternal terdokumentasi dan dapat dipertanggung jawabkan. Penulisan penjelasan pada masing-masing Domain dapat menyesuaikan karakteristik penilaian dan kriteria tingkat kematangannya. Berikut ini
jdih.menpan.go.id
223-
merupakan contoh kaidah dalam memberikan penjelasan penilaian visitasi pada aplikasi pemantauan dan evaluasi SPBE bagi Asesor Eksternal.
Kaidah Penulisan Penjelasan Penilaian Visitasi Bagi Asesor Eksternal yang Melakukan Klarifikasi/Koreksi Pada Domain Kebijakan, Domain Tata Kelola, Domain Manajemen, dan Domain Layanan (Indikator 1-47).
Klarifikasi telah dilakukan terhadap Indikator <
Berdasarkan penjelasan dan data dukung tambahan yang disampaikan pada saat visitasi, maka <
Hasil penilaian visitasi menggambarkan<
Berikut ini merupakan salah satu contoh uraian penjelasan pada salah satu indikator yang dilakukan klarifikasi/koreksi pada penilaian visitasi, yaitu pada Indikator 16 Tingkat Kematangan Layanan Pusat Data Instansi Pusat/ Pemerintah Daerah:

jdih.menpan.go.id
58-
anggaran SPBE yang seluruhnya telah dikonsultasikan dengan unit pengelola TIK dan didokumentasikan secara formal.
Level 4 Kriteria Level Kriteria tingkat 3 telah terpenuhi. Seluruh Rencana dan Anggaran SPBE Instansi Pusat/Pemerintah Daerah telah terpadu dan dapat dikendalikan oleh unit kerja/perangkat daerah yang menjalankan fungsi perencanaan dan penganggaran. Selain itu, Rencana dan Anggaran SPBE telah direviu dan dievaluasi secara periodik.
Kriteria pemenuhan Level Seluruh Rencana dan Anggaran SPBE Instansi Pusat/Pemerintah Daerah telah terpadu dan terkendali pada unit kerja/perangkat daerah yang menjalankan fungsi perencanaan dan penganggaran di Instansi Pusat/Pemerintah Daerah yang dituangkan dalam rencana kerja dan anggaran dan telah dilakukan reviu dan/atau evaluasi secara periodik.
Kriteria Bukti Dukung 1) Dokumen SOP terkait proses penyusunan Anggaran SPBE terpadu dan/atau Dokumen RKA/KL atau DPA-SKPD terkait Rencana dan Anggaran SPBE terpadu yang dikendalikan oleh unit kerja/perangkat daerah yang menjalankan fungsi perencanaan dan penganggaran dan didokumentasikan secara formal;
2) Terdapat notulensi/catatan/laporan hasil evaluasi/reviu terkait Rencana dan Anggaran SPBE yang masih berlaku (<2 tahun);
3) Hasil evaluasi/reviu yang berisi konten isu/permasalahan dan rekomendasi perbaikan yang aktual; dan

jdih.menpan.go.id
106-
Daerah melalui pemanfaatan sistem aplikasi manajemen pengetahuan SPBE.
Level 4 Kriteria Level Kriteria tingkat 3 telah terpenuhi, semua unit kerja/perangkat daerah telah menerapkan Manajemen Pengetahuan SPBE dengan menggunakan sistem aplikasi manajemen pengetahuan yang terintegrasi serta telah dilakukan reviu dan evaluasi terhadap penerapan Manajemen Pengetahuan SPBE.
Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah menerapkan Manajemen Pengetahuan SPBE di seluruh unit kerja/perangkat daerah dengan memanfaatkan aplikasi sistem manajemen pengetahuan SPBE yang telah terintegrasi dengan sistem manajemen pengetahuan SPBE di tingkat nasional, serta telah dilakukan reviu dan/atau evaluasi secara berkala.
Kriteria Bukti Dukung 1) Konteks penerapan Manajemen Pengetahuan yang menguraikan seluruh pemenuhannya sesuai dengan pedoman/standar Manajemen Pengetahuan yang telah ditentukan/ditetapkan dan terdokumentasi secara formal.
2) Bukti hasil penerapan manajemen pengetahuan berupa pengetahuan-pengetahuan baru yang telah dibagi pakai.
3) Terdapat notulensi/catatan/laporan hasil reviu/evaluasi terkait penerapan Manajemen Pengetahuan SPBE yang masih berlaku (<2 tahun).
4) Hasil reviu/evaluasi yang berisi konten isu/permasalahan dan rekomendasi perbaikan yang aktual.
5) Bukti undangan rapat reviu/evaluasi penerapan Manajemen Pengetahuan SPBE, dan/atau dokumentasi aktivitas-aktivitas evaluasi penerapan Manajemen Pengetahuan SPBE (opsional).

Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah memiliki dokumen Peta Rencana SPBE yang dituangkan dalam rencana kerja dan anggaran dan telah dilakukan reviu dan/atau evaluasi secara periodik. Kriteria Bukti Dukung 1) Dokumen yang memuat Peta Rencana SPBE yang didalamnya mencakup seluruh muatan Peta Rencana SPBE dan Dokumen Rencana Kerja dan Anggaran 3 (tiga) tahun terakhir yang didalamnya tercantum program/kegiatan yang selaras dengan Peta Rencana SPBE tersebut; 2) Terdapat notulensi/catatan/laporan hasil evaluasi/reviu terkait Peta Rencana SPBE yang masih berlaku (<2 tahun); 3) Hasil evaluasi/reviu yang berisi konten isu/permasalahan dan rekomendasi perbaikan yang aktual; dan 4) Bukti undangan rapat evaluasi Peta Rencana SPBE, dan/atau dokumentasi aktivitas-aktivitas evaluasi Peta Rencana SPBE (opsional). Level 5 Kriteria Level Kriteria tingkat 4 telah terpenuhi dan dokumen Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah telah dilakukan pemutakhiran sebagai tindak lanjut hasil reviu dan evaluasi. Kriteria pemenuhan Level Dokumen Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah telah dilakukan pemutakhiran dan/atau telah terdapat upaya perbaikan berkelanjutan terhadap Peta Rencana SPBE sebagai tindak lanjut rekomendasi hasil reviu dan/atau evaluasi. Tingkat kematangan level 5 (lima) dapat dipertahankan: a) dengan melakukan reviu terhadap Peta Rencana SPBE; dan b) dengan melakukan tindak lanjut berupa penyempurnaan terhadap Peta Rencana SPBE sesuai hasil

Level 1 Kriteria Level Rencana dan Anggaran SPBE belum atau telah tertuang dalam rencana kerja dan anggaran tahunan. Kriteria pemenuhan Level Rencana dan Anggaran SPBE Instansi Pusat/Pemerintah Daerah belum atau sudah tertuang dalam RKA/DIPA. Kriteria Bukti Dukung Dokumen RKA/KL atau DPA-SKPD yang berisi program/kegiatan penerapan SPBE; Terdapat notulensi/catatan/laporan hasil pembahasan penyusunan Rencana dan Anggaran SPBE, bukti undangan rapat penyusunan Rencana dan Anggaran SPBE, dan/atau dokumentasi aktivitas-aktivitas penyusunan Rencana dan Anggaran SPBE. Level 2 Kriteria Level Kriteria tingkat 1 telah terpenuhi dan sebagian Rencana dan Anggaran SPBE pada unit kerja/perangkat daerah dikonsultasikan kepada unit pengelola TIK di Instansi Pusat/Pemerintah Daerah. Kriteria pemenuhan Level Rencana dan Anggaran SPBE Instansi Pusat/Pemerintah Daerah sebagian dikonsultasikan kepada unit pengelola TIK di Instansi Pusat/Pemerintah Daerah. Kriteria Bukti Dukung Dokumen RKA/KL atau DPA-SKPD yang memuat anggaran SPBE; Dokumen yang berisi hasil konsultasi sebagian anggaran SPBE dengan unit pengelola TIK dan didokumentasikan secara formal. Level 3 Kriteria Level Kriteria tingkat 2 telah terpenuhi dan seluruh Rencana dan Anggaran SPBE pada unit kerja/perangkat daerah dikonsultasikan kepada unit pengelola TIK di Instansi Pusat/Pemerintah Daerah. Kriteria pemenuhan Level Seluruh Rencana dan Anggaran SPBE Instansi Pusat/Pemerintah Daerah dikonsultasikan kepada unit pengelola TIK di

seluruhnya (kompetensi di bidang Proses Bisnis Pemerintahan, Arsitektur SPBE, Data dan Informasi, Keamanan SPBE, Aplikasi SPBE, dan Infrastruktur SPBE). Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah menerapkan Manajemen SDM SPBE yang memuat serangkaian proses manajemen SDM SPBE mulai dari perencanaan, pengembangan, pembinaan, dan pendayagunaan sumber daya manusia dalam SPBE dan telah memenuhi seluruh kompetensi sumber daya manusia SPBE. Kriteria Bukti Dukung Konteks penerapan Manajemen SDM SPBE yang selaras dengan arah dan perencanaan programnya dan terdokumentasi secara formal, dan pelaksanaannya sudah memenuhi seluruh kompetensi sumber daya manusia SPBE. Level 4 Kriteria Level Kriteria tingkat 3 telah terpenuhi, peningkatan dan penilaian kompetensi Sumber Daya Manusia SPBE telah dilakukan. Selain itu, pemenuhan kompetensi Sumber Daya Manusia SPBE telah dilakukan reviu dan evaluasi secara periodik. Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah menyusun strategi pelaksanaan Manajemen SDM SPBE yang ditetapkan oleh Tim Koordinasi SPBE, diterapkan kepada seluruh unit kerja/perangkat daerah, serta telah dilakukan reviu dan/atau evaluasi secara berkala. Kriteria Bukti Dukung 1) Terdapat dokumentasi formal arah kebijakan strategis Manajemen SDM SPBE yang ditetapkan oleh Tim Koordinasi SPBE kepada seluruh unit kerja/perangkat daerah. 2) Terdapat notulensi/catatan/laporan hasil evaluasi/reviu terkait penerapan Manajemen SDM SPBE yang masih berlaku

## ❓ Pertanyaan pengguna:
Jika "Rencana dan Anggaran SPBE Instansi Pusat Pemerintah Daerah telah terpadu dan dapat dikendalikan oleh unit kerja/perangkat daerah yang menjalankan fungsi perencanaan dan penganggaran dan telah direviu serta dievaluasi secara periodik:" Maka dapat diberikan level...


## ✅ Jawaban Anda:


> Finished chain.

> Finished chain.
Berdasarkan pedoman pemantauan dan evaluasi SPBE, dengan diberikannya informasi tahapan, kriteria pemenuhan level dan bukti dukung maka indeks SPBE diberikan:

{
  "Penilaian": {
    "Level": 4,
    "Indikator": 16,
    "Aspek": 5,
    "Domain": 2
  }
}

Alasan penilaian diatas karena Rencana dan Anggaran SPBE Instansi Pusat/Pemerintah Daerah telah terpadu dan dapat dikendalikan oleh unit kerja/perangkat daerah yang menjalankan fungsi perencanaan dan penganggaran dan telah direviu serta dievaluasi secara periodik, sesuai dengan kriteria level 4 pada aspek Penerapan Manajemen SPBE (Aspek 5) dan Domain Tata Kelola (Domain 2), dengan indikator 16 yang terkait dengan Tingkat Kematangan Layanan Pusat Data Instansi Pusat/Pemerintah Daerah.
✅ Question 2 processed successfully
⏳ Menunggu 30 detik...
Processing question 3/5: Berapa nilai indeks domain yang masih dibawah targ...

INFO:langchain.retrievers.multi_query:Generated queries: ['Berapa nilai indeks domain yang belum mencapai target pada periode 2021-2023?', 'Nilai indeks domain mana yang masih di bawah target selama tahun 2021 hingga 2023?', 'Indeks domain apa yang memiliki nilai di bawah target pada tahun 2021, 2022, dan 2023?']

> Entering new StuffDocumentsChain chain...


> Entering new LLMChain chain...
Prompt after formatting:
Anda adalah asisten asesor SPBE yang detail, khususnya dalam memberikan informasi Sistem Pemerintahan Berbasis Elektronik (SPBE) Indonesia.

terkait Sistem Pemerintahan Berbasis Elektronik (SPBE). Didalamnya ada 4 Domain yang disingkat D (contoh: D1,D2,D3,D4), lalu ada 8 Aspek yang disingkat A (contoh: A2, A5) dan 47 Indikator yang disingkat ID (contoh: ID-3, ID-23). jadi struktur dari SPBE ada 3 unsur tadi domain, aspek, dan indikator, dan penilaian indikator ada kriteria level nya yaitu level 1-5,  dengan level 5 paling tinggi nya.
jika ditanya terkait Indeks SPBE Nasional, tolong cari dan referensikan ke Tabel 1. Indeks SPBE Nasional (2021 - 2023)

Ada 4 Domain utama SPBE:
1. Domain 1: Kebijakan
2. Domain 2: Tata Kelola
3. Domain 3: Manajemen
4. Domain 4: Layanan

Ada 8 Aspek utama SPBE:
1. Aspek 1: Kebijakan Tata Kelola SPBE
2. Aspek 2: Perencanaan Strategis SPBE
3. Aspek 3: Teknologi Informasi dan Komunikasi
4. Aspek 4: Penyelenggaraan SPBE
5. Aspek 5: Penerapan Manajemen SPBE
6. Aspek 6: Audit TIK
7. Aspek 7: Layanan Administrasi Pemerintahan
8. Aspek 8: Layanan Publik

Ada 47 Indikator utama SPBE:
1. Indikator 1-10 berada di Domain Kebijakan (bobot 13%)
2. Indikator 11-20 berada di Domain Tata Kelola (bobot 25%)
3. Indikator 21-31 berada di Domain Manajemen (bobot 16,5%)
4. Indikator 32-47 berada di Domain Layanan (bobot 45,5%)

Ada 5 Tingkat Kematangan Domain Kebijakan, Tata Kelola, dan Manajemen:
1. Rintisan
2. Terkelola
3. Terdefinisi
4. Terpadu dan Terukur
5. Optimum

Sedangkan untuk Domain Layanan:
1. Informasi
2. Interaksi
3. Transaksi
4. Kolaborasi
5. Optimum

## 🎯 Aturan Menjawab dan Tugas:
1. Menjawab pertanyaan umum tentang SPBE secara akurat.
2. Menunjukkan domain, aspek, dan indikator juga level terkait dengan pertanyaan pengguna berdasarkan pedoman SPBE jika pengguna menanyakan indikator/aspek/domain dan level nya juga memberikan alasan pemberian penilaian dari deskripsi ataupun kriteria, bukti lainnya.
3. Sebelum sebuah tingkat kematangan berada pada suatu level, harus memenuhi semua kriteria dan bukti dukung level sebelumnya kecuali level 1 yang masih awal.

## 📢 Tanggapan Anda harus mengikuti aturan berikut:
- Jika pengguna hanya ingin ringkasan, berikan jawaban singkat.
- jawab dengan konkrit tidak terlalu panjang dan jelas.
- Jika pertanyaan tidak terkait dengan SPBE dan pedoman SPBE, berikan respons berikut:
  - *"Maaf, pertanyaan tersebut tidak terkait dengan SPBE KemenpanRB. Saya hanya dapat memberikan jawaban berdasarkan konteks tersebut."
---

## 🔍 Konteks Riwayat Percakapan:


## 🔍 Konteks yang diberikan dari dokumen:
Berdasarkan capaian Indeks SPBE Nasional sebagaimana dimaksud secara umum menunjukkan peningkatan dari tahun ke tahun, namun dinamika perkembangan strategis penyelarasan implementasinya terdapat Indeks Domain yang masih di bawah target (<2,60) yaitu Indeks Domain Tata Kelola dan Indeks Domain Manajemen. Hal tersebut akan menjadi salah satu fokus yang dituangkan dalam Pedoman agar instrumen yang digunakan untuk melakukan pengukuran tingkat kematangan dapat dipahami dan diimplementasikan dengan komprehensif.
Selanjutnya, untuk dapat menyatukan pemahaman serta memberikan acuan baku, maka berdasarkan amanat Pasal 9 Peraturan Menteri PANRB No. 59 Tahun 2020 perlu dibentuk suatu pedoman teknis yang ditetapkan oleh Menteri PANRB untuk memudahkan setiap pihak yang terlibat dalam melaksanakan pemantauan dan evaluasi SPBE (dhi. Asesor Internal pada Instansi Pusat dan Pemerintah Daerah, Asesor Ekternal, serta Tim Pelaksanaan Pemantauan dan Evaluasi SPBE Kementerian PANRB). Pedoman dimaksud disusun untuk memudahkan pihak yang terlibat dalam mengimplementasikan SPBE beserta pengukuran tingkat kematangannya secara komprehensif. Untuk itu, agar pemantauan dan evaluasi SPBE dapat dilaksanakan dengan baik, maka diperlukan adanya penyempurnaan pada pedoman teknis pemantauan dan evaluasi SPBE.
jdih.menpan.go.id
4-
B. Maksud dan Tujuan

Peraturan Menteri PANRB Nomor 59 Tahun 2020 mengatur mengenai tahap perencanaan, pelaksanaan, dan pelaporan atas pemantauan dan evaluasi penerapan SPBE yang telah dilakukan. Selain itu, Peraturan Menteri tersebut juga mengatur ruang lingkup pemantauan dan evaluasi SPBE yang mencakup domain kebijakan SPBE, tata kelola SPBE, manajemen SPBE, dan layanan SPBE yang dapat menggambarkan hasil penyelenggaraan SPBE baik pada Instansi Pusat maupun Pemerintah Daerah.
Hasil pelaksanaan pemantauan dan evaluasi SPBE diharapkan menjadi tolok ukur bagi Instansi Pusat dan Pemerintah Daerah untuk melakukan perbaikan pada aspek domain SPBE dimaksud, yang direpresentasikan berdasarkan nilai indeks SPBE. Tabel 1 di bawah ini menggambarkan perkembangan rata-rata capaian Indeks SPBE nasional dari tahun 2021-2023, yakni sejak dilaksanakannya Peraturan Menteri PANRB No. 59 Tahun 2020, sebagaimana tergambar dalam tabel di bawah ini.
3-
Tabel 1. Indeks SPBE Nasional (2021 – 2023)
Deskripsi 2021 2022 2023 Indeks SPBE Nasional 2,24 2,34 2,79 Indeks Domain Kebijakan 2,21 2,39 2,94 Indeks Domain Tata Kelola 1,89 1,85 2,29 Indeks Domain Manajemen 1,23 1,32 1,66 Indeks Domain Layanan 2,81 2,96 3,47 Jumlah IPPD Kategori “Baik” 159 237 388 Jumlah Responden (IPPD) 517 554 621

## ❓ Pertanyaan pengguna:
Berapa nilai indeks domain yang masih dibawah target pada tahun 2021-2023?

## ✅ Jawaban Anda:


> Finished chain.

> Finished chain.
Nilai indeks domain yang masih di bawah target (<2,60) pada tahun 2021-2023 adalah Indeks Domain Tata Kelola dan Indeks Domain Manajemen.

Berikut adalah nilai indeks domain tersebut pada tahun 2021-2023:
- Indeks Domain Tata Kelola: 1,89 (2021), 1,85 (2022), 2,29 (2023)
- Indeks Domain Manajemen: 1,23 (2021), 1,32 (2022), 1,66 (2023)

Kedua indeks domain ini masih di bawah target yang ditetapkan, yaitu <2,60.
✅ Question 3 processed successfully
⏳ Menunggu 30 detik...
Processing question 4/5: Sebuah IPPD melampirkan Peta Rencana SPBE yang tel...

INFO:langchain.retrievers.multi_query:Generated queries: ['Berikut adalah tiga versi alternatif dari pertanyaan asli untuk membantu mengatasi keterbatasan pencarian kesamaan berbasis jarak:', '1. Apa tingkat yang sesuai untuk sebuah IPPD yang telah melampirkan Peta Rencana SPBE yang lengkap dan formal, mencakup aspek-aspek seperti Tata Kelola, Manajemen, Layanan, Arsitektur, Aplikasi, Keamanan, dan Audit TIK?', '2. Bagaimana menentukan level yang tepat untuk sebuah Instansi Pusat Pemerintah Daerah yang telah mengembangkan dan mendokumentasikan Peta Rencana SPBE secara menyeluruh, termasuk seluruh komponen yang diperlukan seperti Tata Kelola SPBE, Manajemen SPBE, Layanan SPBE, Arsitektur SPBE, Aplikasi SPBE, Keamanan SPBE, dan Audit TIK?', '3. Berdasarkan informasi yang diberikan tentang sebuah IPPD yang telah menyusun Peta Rencana SPBE yang komprehensif, mencakup berbagai aspek seperti Tata Kelola, Manajemen, Layanan, Arsitektur, Aplikasi, Keamanan, dan Audit TIK, apa level yang paling sesuai untuk diberikan mengingat cakupan dan kelengkapan dokumen Peta Rencana tersebut?']

> Entering new StuffDocumentsChain chain...


> Entering new LLMChain chain...
Prompt after formatting:

Anda adalah asisten asesor SPBE yang detail, khususnya dalam membantu auditing Sistem Pemerintahan Berbasis Elektronik (SPBE) Indonesia.

terkait Sistem Pemerintahan Berbasis Elektronik (SPBE). Didalamnya ada 4 Domain yang disingkat D (contoh: D1,D2,D3,D4), lalu ada 8 Aspek yang disingkat A (contoh: A2, A5) dan 47 Indikator yang disingkat ID (contoh: ID-3, ID-23). jadi struktur dari SPBE ada 3 unsur tadi domain, aspek, dan indikator, dan penilaian indikator ada kriteria level nya yaitu level 1-5,  dengan level 5 paling tinggi nya.
jika ditanya terkait Indeks SPBE Nasional, tolong cari dan referensikan ke Tabel 1. Indeks SPBE Nasional (2021 - 2023)

Ada 4 Domain utama SPBE:
1. Domain 1: Kebijakan
2. Domain 2: Tata Kelola
3. Domain 3: Manajemen
4. Domain 4: Layanan

Ada 8 Aspek utama SPBE:
1. Aspek 1: Kebijakan Tata Kelola SPBE
2. Aspek 2: Perencanaan Strategis SPBE
3. Aspek 3: Teknologi Informasi dan Komunikasi
4. Aspek 4: Penyelenggaraan SPBE
5. Aspek 5: Penerapan Manajemen SPBE
6. Aspek 6: Audit TIK
7. Aspek 7: Layanan Administrasi Pemerintahan
8. Aspek 8: Layanan Publik

Ada 47 Indikator utama SPBE:
1. Indikator 1-10 berada di Domain Kebijakan (bobot 13%)
2. Indikator 11-20 berada di Domain Tata Kelola (bobot 25%)
3. Indikator 21-31 berada di Domain Manajemen (bobot 16,5%)
4. Indikator 32-47 berada di Domain Layanan (bobot 45,5%)

Ada 5 Tingkat Kematangan Domain Kebijakan, Tata Kelola, dan Manajemen:
1. Rintisan
2. Terkelola
3. Terdefinisi
4. Terpadu dan Terukur
5. Optimum

Sedangkan untuk Domain Layanan:
1. Informasi
2. Interaksi
3. Transaksi
4. Kolaborasi
5. Optimum

## 🎯 Aturan Menjawab dan Tugas:
1. Dalam memberikan penilaian level berapa sebuah indikator, maka pastikan memenuhi kriteria pemenuhan level dan kriteria bukti dukung, ini harus ada jika melakukan audit, kalau tidak ada maka mintakan kepada pengguna hal tersebut.
2. Menunjukkan domain, aspek, dan indikator juga level terkait dengan pertanyaan pengguna berdasarkan pedoman SPBE jika pengguna menanyakan indikantor/aspek/doman dan level nya juga memberikan alasan pemberian penilaian dari deskripsi ataupun kriteria, bukti lainnya.
3. Sebelum sebuah tingkat kematangan berada pada suatu level, harus memenuhi semua kriteria dan bukti dukung level sebelumnya kecuali level 1 yang masih awal.
4. Kamu akan diberikan konteks dibawah, jadi pastikan hal yang dibutuhkan untuk penilaian tersedia, jangan menjawab jika konteks tidak tersedia

## 📢 Tanggapan Anda harus mengikuti aturan berikut:
- jawab dengan konkrit tidak terlalu panjang dan jelas.
- Jika pertanyaan tidak terkait dengan SPBE dan pedoman SPBE, berikan respons berikut:
  - *"Maaf, pertanyaan tersebut tidak terkait dengan SPBE KemenpanRB. Saya hanya dapat memberikan jawaban berdasarkan konteks tersebut."
---
Berikut contoh format jawaban yang harus kamu lakukan:
<contoh format jawaban>
Berdasarkan pedoman pemantauan dan evaluasi SPBE.....dengan diberikannya informasi tahapan, kriteria pemenuhan level dan bukti dukung maka indeks SPBE diberikan:

{
  "Penilaian": {
    "Level": 5,
    "Indikator": 3,
    "Aspek": 2,
    "Domain": 1
  }
}

alasan penilaian diatas karena.....level.....indikator....aspek....domain...sesuai standard dari pedoman evaluasi SPBE.
</contoh format jawaban>
yang titik diatas kamu harus isi alasannya, dan sesuai format

## 🔍 Konteks Riwayat Percakapan:


## 🔍 Konteks yang diberikan dari dokumen:
d. Tidak menerima gratifikasi terkait dengan penugasan sebagai asesor dalam bentuk apapun.
234-
B.2. Untuk menerapkan prinsip Objektivitas, Asesor diharapkan:
a. Tidak berpartisipasi dalam kegiatan atau hubungan apapun yang dapat menimbulkan konflik dengan kepentingan penugasannya sebagai asesor, atau yang dapat menimbulkan prasangka, atau yang meragukan kemampuannya untuk dapat melaksanakan tugas dan memenuhi tanggung jawab profesinya secara objektif; b. Tidak menerima sesuatu dalam bentuk apapun yang dapat mengganggu atau patut diduga mengganggu pertimbangan profesionalnya; dan c. Mengungkapkan semua fakta material yang diketahui, yaitu fakta yang jika tidak diungkapkan dapat mengubah atau mempengaruhi penilaian dalam pelaksanaan pemantauan dan evaluasi SPBE.
B.3. Untuk menerapkan prinsip Kerahasiaan, Asesor diharapkan:
a. Berhati-hati dalam penggunaan dan pelindungan informasi yang diperoleh dalam tugasnya; dan b. Tidak menggunakan informasi untuk keuntungan pribadi atau dengan cara apapun yang akan bertentangan dengan ketentuan atau merugikan tujuan pelaksanaan pemantauan dan evaluasi SPBE yang sah dan etis.
B.4. Untuk menerapkan prinsip Kompetensi, Asesor diharapkan:
a. Memberikan kontribusi pelaksanaan tugas sesuai dengan pengetahuan, keahlian dan keterampilan, serta pengalaman yang diperlukan; dan b. Melakukan kegiatan pemantauan dan evaluasi SPBE sesuai dengan ketentuan yang berlaku.

Namun disisi lain, Badan xxx masih terdapat beberapa kelemahan, khususnya pada aspek Layanan Publik. Layanan Publik memang sudah direncanakan pada Arsitektur SPBE dan Peta Rencana SPBE dan berdasarkan penerapan Rencana dan Anggaran SPBE sudah terakomodasi, namun pada penerapannya, kapabilitas fungsi teknis dari layanan tersebut masih rendah, dimana masih banyak aplikasi publik yang dibangun secara sendiri-sendiri, sehingga tidak memanfaatkan potensi transaksi dan integrasi terhadap layanan SPBE lainnya. Hal ini menyebabkan Layanan Publik yang diberikan tidak efektif dan optimal pemanfaatannya
Pada Aspek Kebijakan Layanan yang masih bersifat mengatur secara internal perlu ditingkatkan untuk mengakomodasi arah kolaborasi dan integrasi serta dapat ditingkatkan sesuai kebutuhan Badan xxx. Aspek Layanan Publik yang tingkat kematangannya masih rendah, agar dapat menggunakan aplikasi umum berbagi pakai yang telah tetapkan secara nasional, atau melakukan replikasi dari layanan-layanan publik sejenis yang dibangun oleh Instansi lainnya. Diharapkan dapat melakukan inisiatif penerapan Manajemen SPBE sesuai dengan Peraturan yang berlaku, sehingga pada pelaksanaan evaluasi SPBE selanjutnya sudah dapat memenuhi indikator dan kriteria penilaian sesuai target
G. Tata Cara dan Kaidah Penyusunan Hasil Reviu Bagi Tim Reviu.

Catatan Penilaian Visit
Klarifikasi tidak dilakukan terhadap Indikator <<No, dan Subste Berdasarkan hasil verifikasi <
Gambar 4. Penilaian Visitasi Pada Aplikasi
Asesor Eksternal dapat melakukan klarifikasi, verifikasi, dan validasi kepada Asesor Internal terhadap indikator yang memerlukan perincian dan data dukung tambahan. Dalam memberikan penjelasan dalam penilaian, Asesor Eksternal agar mengacu pada kaidah berikut ini, sehingga uraian hasil penilaian eksternal terdokumentasi dan dapat dipertanggung jawabkan. Penulisan penjelasan pada masing-masing Domain dapat menyesuaikan karakteristik penilaian dan kriteria tingkat kematangannya. Berikut ini
jdih.menpan.go.id
223-
merupakan contoh kaidah dalam memberikan penjelasan penilaian visitasi pada aplikasi pemantauan dan evaluasi SPBE bagi Asesor Eksternal.
Kaidah Penulisan Penjelasan Penilaian Visitasi Bagi Asesor Eksternal yang Melakukan Klarifikasi/Koreksi Pada Domain Kebijakan, Domain Tata Kelola, Domain Manajemen, dan Domain Layanan (Indikator 1-47).
Klarifikasi telah dilakukan terhadap Indikator <
Berdasarkan penjelasan dan data dukung tambahan yang disampaikan pada saat visitasi, maka <
Hasil penilaian visitasi menggambarkan<
Berikut ini merupakan salah satu contoh uraian penjelasan pada salah satu indikator yang dilakukan klarifikasi/koreksi pada penilaian visitasi, yaitu pada Indikator 16 Tingkat Kematangan Layanan Pusat Data Instansi Pusat/ Pemerintah Daerah:

Kriteria Bukti Dukung 1) Terdapat notulensi/catatan/laporan hasil reviu/evaluasi dan rekomendasi tindak lanjut Arsitektur SPBE, yang dilengkapi dengan bukti undangan rapat pembahasan penyempurnaan Arsitektur SPBE, dan/atau dokumentasi aktivitas-aktivitas analisis komparasi atau penyempurnaan Arsitektur SPBE;
jdih.menpan.go.id
53-
2) Dokumen Arsitektur SPBE as-is Instansi Pusat/Pemerintah Daerah yang berlaku; dan
3) Dokumen Arsitektur SPBE Instansi Pusat/Pemerintah Daerah to-be atau penyempurnaan yang telah diberlakukan..
INDIKATOR 12
Domain Aspek Ind Kuesioner D2 A2 ID-12 Tingkat Kematangan Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah.
Deskripsi Indikator: a. Peta Rencana SPBE adalah dokumen yang mendeskripsikan arah dan langkah penyiapan dan pelaksanaan SPBE yang terintegrasi.
b. Peta Rencana SPBE memuat:
Tata Kelola SPBE;
Manajemen SPBE;
Layanan SPBE;
Infrastruktur SPBE;
Aplikasi SPBE;
Keamanan SPBE; dan
Audit TIK.
Ketentuan Penilaian: Penilaian dilakukan terhadap bukti dukung dokumen Peta Rencana SPBE yang memenuhi kriteria ruang lingkup Peta Rencana SPBE dan terdokumentasi secara formal.
Contoh Bukti Dukung: Bukti dukung tingkat kematangan dilampirkan berupa dokumen sesuai huruf a dan b. Data Pendukung dapat disampaikan lebih dari 1 (satu) jenis dokumen.

INDIKATOR 30
Domain Aspek Ind Kuesioner D3 A5 ID-30 Tingkat Kematangan Pelaksanaan Audit Aplikasi SPBE. Deskripsi Indikator: a. Audit Aplikasi SPBE Instansi Pusat dan Pemerintah Daerah dilaksanakan berdasarkan standar dan tata cara pelaksanaan Audit Aplikasi SPBE. b. Audit Aplikasi SPBE terdiri atas: 1. Audit Aplikasi Umum
120-
2. Audit Aplikasi Khusus
c. Standar/pedoman audit dapat berupa standar internal Instansi Pusat/Pemerintah Daerah, standar/pedoman nasional, atau standar/pedoman internasional.
Ketentuan Penilaian: Penilaian dilakukan terhadap bukti dukung pelaksanaan Audit Aplikasi SPBE Instansi Pusat/Pemerintah Daerah yang memenuhi kriteria ruang lingkup, serta terdokumentasi secara formal. Bukti dukung yang memenuhi kriteria penilaian merupakan bukti dukung pelaksanaan Audit Aplikasi SPBE yang dilakukan dalam kurun waktu 2 (dua) tahun terakhir.
Contoh Bukti Dukung: Bukti dukung tingkat kematangan dilampirkan berupa dokumentasi penerapan Audit Aplikasi sesuai huruf a dan b.

Contoh Bukti Dukung: Bukti dukung tingkat kematangan dilampirkan berupa dokumen sesuai huruf a dan b. Data Pendukung dapat disampaikan lebih dari 1 (satu) jenis dokumen.
Level Kriteria Level Konsep dokumen Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah belum atau telah tersedia. 1 Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah belum atau sudah memiliki konsep dokumen Peta Rencana SPBE dimaksud atau masih dalam proses penyusunan. Kriteria Bukti Dukung Dokumen berupa draft/rancangan Peta Rencana SPBE; Terdapat notulensi/catatan/laporan hasil penyusunan rancangan Peta Rencana SPBE, bukti undangan rapat
jdih.menpan.go.id
54-
penyusunan rancangan Peta Rencana SPBE, dan/atau dokumentasi aktivitas-aktivitas penyusunan Peta Rencana SPBE.
Dokumen Peta Rencana SPBE telah tersedia. Kondisi: dokumen Peta Rencana SPBE belum mengatur muatan Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah secara lengkap (Tata Kelola SPBE, Manajemen SPBE, Layanan SPBE, Infrastruktur SPBE, Aplikasi SPBE, Keamanan SPBE, Audit Teknologi SPBE dan Audit TIK).
Level 2
Kriteria Level
Instansi Pusat/Pemerintah Daerah sudah memiliki dokumen Peta Rencana SPBE yang mencakup sebagian muatan Peta Rencana SPBE.
Kriteria pemenuhan Level
Dokumen yang memuat Peta Rencana SPBE yang didalamnya mencakup sebagian muatan Peta Rencana SPBE serta telah didokumentasikan secara formal.
Kriteria Bukti Dukung

Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah melakukan kegiatan Audit Keamanan SPBE namun masih bersifat sementara (adhoc). Kriteria Bukti Dukung Draf/rancangan pelaksanaan Audit Keamanan SPBE, notulensi/catatan penyusunan rancangan pelaksanaan Audit Keamanan SPBE, bukti undangan rapat penyusunan rancangan pelaksanaan Audit Keamanan SPBE dan/atau dokumentasi aktivitas-aktivitas pelaksanaan Audit Keamanan SPBE. Level 2 Kriteria Level Kriteria tingkat 1 telah terpenuhi dan kegiatan Audit Keamanan dilaksanakan sesuai dengan perencanaan yang berkesinambungan. Kondisi: Kegiatan Audit Keamanan dilaksanakan tanpa standar/pedoman. Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah melakukan Audit Keamanan SPBE melalui program kegiatan yang sesuai dan selaras dengan Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah, namun pemeriksaan hanya meliputi sebagian hal pokok teknis yang disyaratkan. Pelaksanaan Audit Keamanan SPBE dilakukan secara rutin minimal 2 tahun sekali. Kriteria Bukti Dukung Perencanaan program kerja/aktivitas kegiatan pelaksanaan Audit Keamanan SPBE tertuang di dalam dokumen Peta Rencana SPBE yang masih berlaku dan terdokumentasi secara formal, namun penerapannya belum mengacu pada pedoman/standar Audit Keamanan SPBE yang telah ditentukan/ditetapkan dan hanya terhadap sebagian dari hal pokok teknis yang disyaratkan. Level 3 Kriteria Level Kriteria tingkat 2 telah terpenuhi dan kegiatan Audit Keamanan dilaksanakan sesuai dengan

Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah belum atau sudah membangun Forum Kolaborasi Penerapan SPBE namun bersifat sementara (ad-hoc). Kriteria Bukti Dukung Notulensi/catatan/laporan hasil pembentukan Forum Kolaborasi Penerapan SPBE, bukti undangan rapat pembentukan Forum Kolaborasi Penerapan SPBE, dan/atau dokumentasi aktivitas-aktivitas pembentukan Forum Kolaborasi Penerapan SPBE. Level 2 Kriteria Level Kriteria tingkat 1 telah terpenuhi dan kolaborasi antar unit kerja/perangkat daerah di Instansi Pusat/Pemerintah Daerah dalam penerapan SPBE telah dilaksanakan sesuai perencanaan. Kondisi: Kolaborasi antar unit kerja/perangkat daerah di Instansi Pusat/Pemerintah Daerah dalam penerapan SPBE tidak dibentuk secara formal. Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah sudah melakukan kolaborasi penerapan SPBE antar unit kerja/perangkat daerah dan telah menyusun perencanaan, namun belum ditetapkan secara formal. Kriteria Bukti Dukung Dokumentasi aktivitas kolaborasi penerapan SPBE antar unit kerja/perangkat daerah sesuai dengan yang telah direncanakan oleh Instansi Pusat/Pemerintah Daerah dan/atau dilengkapi bukti-bukti undangan rapat notulensi/catatan/laporan kolaborasi penerapan SPBE. Level 3 Kriteria Level Kriteria tingkat 2 telah terpenuhi dan kolaborasi antar unit kerja/perangkat daerah di Instansi Pusat/Pemerintah Daerah dalam penerapan SPBE telah dilaksanakan oleh tim yang dibentuk secara formal. Kondisi: Kolaborasi antar unit kerja/perangkat

56-
Rencana SPBE, yang dapat dilengkapi dengan bukti undangan rapat pembahasan penyempurnaan Peta Rencana SPBE, dan/atau dokumentasi aktivitas-aktivitas analisis komparasi atau penyempurnaan Peta Rencana SPBE;
2) Dokumen yang memuat Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah yang berlaku sebelumnya dan dokumen yang memuat Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah yang telah disempurnakan dan telah ditetapkan; atau
3) Dokumentasi hasil upaya penguatan tata kelola Peta Rencana SPBE sesuai dengan rekomendasi hasil reviu dan/atau evaluasi.
INDIKATOR 13
Domain Aspek Ind Kuesioner D2 A2 ID-13 Tingkat Kematangan Keterpaduan Rencana dan Anggaran SPBE. Deskripsi Indikator: a. Rencana dan Anggaran SPBE adalah dokumen yang mendeskripsikan program, kegiatan dan pemanfaatan anggaran SPBE. b. Rencana dan Anggaran SPBE disusun sesuai dengan proses perencanaan dan penganggaran tahunan pemerintah. c. Rencana dan Anggaran SPBE Instansi Pusat/Pemerintah Daerah berpedoman pada Arsitektur SPBE Instansi Pusat/Pemerintah Daerah dan Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah. Ketentuan Penilaian: Penilaian dilakukan terhadap bukti dukung Keterpaduan Rencana dan Anggaran SPBE yang memenuhi kriteria ruang lingkup Rencana dan Anggaran SPBE dan terdokumentasi secara formal. Contoh Bukti Dukung: Bukti dukung tingkat kematangan dilampirkan berupa dokumen sesuai huruf a, b, dan c. Data Pendukung dapat disampaikan lebih dari 1 (satu) jenis dokumen.
jdih.menpan.go.id
57-

Kriteria pemenuhan Level
Dokumen yang memuat Peta Rencana SPBE yang didalamnya mencakup sebagian muatan Peta Rencana SPBE serta telah didokumentasikan secara formal.
Kriteria Bukti Dukung
Kriteria tingkat 2 telah terpenuhi dan dokumen Peta Rencana SPBE telah mengatur seluruh muatan Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah secara lengkap (Tata Kelola SPBE, Manajemen SPBE, Layanan SPBE, Infrastruktur SPBE, Aplikasi SPBE, Keamanan SPBE, Audit Teknologi SPBE dan Audit TIK).
Level 3
Kriteria Level
Instansi Pusat/Pemerintah Daerah telah memiliki dokumen Peta Rencana SPBE yang mencakup keseluruhan muatan Peta Rencana SPBE.
Kriteria pemenuhan Level
Dokumen yang memuat Peta Rencana SPBE yang didalamnya mencakup seluruh muatan Peta Rencana SPBE serta telah didokumentasikan secara formal.
Kriteria Bukti Dukung
Kriteria tingkat 3 telah terpenuhi dan dokumen Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah telah diterapkan secara konsisten melalui rencana kerja dan anggaran 3 (tiga) tahun terakhir. Selain itu, dokumen Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah telah dilakukan reviu dan evaluasi secara periodik.
Level 4
Kriteria Level
jdih.menpan.go.id
55-

## ❓ Pertanyaan pengguna:
Sebuah IPPD melampirkan Peta Rencana SPBE yang telah didokumentasikan secara formal, dan mengklaim memiliki dokumen Peta Rencana SPBE yang telah mengatur seluruh muatan Peta Rencana SPBE Instansi Pusat Pemerintah Daerah. Dokumen Peta Rencana yang diunggah berisikan muatan Peta Rencana secara lengkap antara lain Tata Kelola SPBE, Manajemen SPBE, Layanan SPBE, Arsitektur SPBE, Aplikasi SPBE, Keamanan SPBE dan Audit TIK. Maka level yang pantas diberikan adalah...


## ✅ Jawaban Anda:


> Finished chain.

> Finished chain.
Berdasarkan pedoman pemantauan dan evaluasi SPBE, dengan diberikannya informasi tahapan, kriteria pemenuhan level dan bukti dukung maka indeks SPBE diberikan:

{
  "Penilaian": {
    "Level": 3,
    "Indikator": 12,
    "Aspek": 2,
    "Domain": 2
  }
}

Alasan penilaian diatas karena IPPD telah memiliki dokumen Peta Rencana SPBE yang mencakup keseluruhan muatan Peta Rencana SPBE, yaitu Tata Kelola SPBE, Manajemen SPBE, Layanan SPBE, Arsitektur SPBE, Aplikasi SPBE, Keamanan SPBE, dan Audit TIK, serta telah didokumentasikan secara formal. Ini sesuai dengan kriteria level 3 pada indikator 12, aspek 2, domain 2.
✅ Question 4 processed successfully
⏳ Menunggu 30 detik...
Processing question 5/5: Dibawah ini merupakan domain-domain dari Arsitektu...

INFO:langchain.retrievers.multi_query:Generated queries: ['Apa saja domain arsitektur SPBE yang tercantum dalam Perpres SPBE, kecuali satu yang tidak termasuk?', ' ', 'Berikut ini adalah daftar domain arsitektur SPBE berdasarkan Perpres SPBE, kecuali salah satu, pilih yang tidak termasuk: domain arsitektur Proses Bisnis, domain arsitektur Manajemen SPBE, domain arsitektur Infrastruktur SPBE, domain arsitektur Aplikasi SPBE, domain arsitektur Keamanan SPBE, domain arsitektur Layanan SPBE, mana yang bukan termasuk?', ' ', 'Domain-domain apa saja yang termasuk dalam arsitektur SPBE menurut Perpres SPBE, dan mana yang tidak termasuk dalam daftar: domain arsitektur Proses Bisnis, domain arsitektur Manajemen SPBE, domain arsitektur Infrastruktur SPBE, domain arsitektur Aplikasi SPBE, domain arsitektur Keamanan SPBE, domain arsitektur Layanan SPBE?']

> Entering new StuffDocumentsChain chain...


> Entering new LLMChain chain...
Prompt after formatting:
Anda adalah asisten asesor SPBE yang detail, khususnya dalam memberikan informasi Sistem Pemerintahan Berbasis Elektronik (SPBE) Indonesia.

terkait Sistem Pemerintahan Berbasis Elektronik (SPBE). Didalamnya ada 4 Domain yang disingkat D (contoh: D1,D2,D3,D4), lalu ada 8 Aspek yang disingkat A (contoh: A2, A5) dan 47 Indikator yang disingkat ID (contoh: ID-3, ID-23). jadi struktur dari SPBE ada 3 unsur tadi domain, aspek, dan indikator, dan penilaian indikator ada kriteria level nya yaitu level 1-5,  dengan level 5 paling tinggi nya.
jika ditanya terkait Indeks SPBE Nasional, tolong cari dan referensikan ke Tabel 1. Indeks SPBE Nasional (2021 - 2023)

Ada 4 Domain utama SPBE:
1. Domain 1: Kebijakan
2. Domain 2: Tata Kelola
3. Domain 3: Manajemen
4. Domain 4: Layanan

Ada 8 Aspek utama SPBE:
1. Aspek 1: Kebijakan Tata Kelola SPBE
2. Aspek 2: Perencanaan Strategis SPBE
3. Aspek 3: Teknologi Informasi dan Komunikasi
4. Aspek 4: Penyelenggaraan SPBE
5. Aspek 5: Penerapan Manajemen SPBE
6. Aspek 6: Audit TIK
7. Aspek 7: Layanan Administrasi Pemerintahan
8. Aspek 8: Layanan Publik

Ada 47 Indikator utama SPBE:
1. Indikator 1-10 berada di Domain Kebijakan (bobot 13%)
2. Indikator 11-20 berada di Domain Tata Kelola (bobot 25%)
3. Indikator 21-31 berada di Domain Manajemen (bobot 16,5%)
4. Indikator 32-47 berada di Domain Layanan (bobot 45,5%)

Ada 5 Tingkat Kematangan Domain Kebijakan, Tata Kelola, dan Manajemen:
1. Rintisan
2. Terkelola
3. Terdefinisi
4. Terpadu dan Terukur
5. Optimum

Sedangkan untuk Domain Layanan:
1. Informasi
2. Interaksi
3. Transaksi
4. Kolaborasi
5. Optimum

## 🎯 Aturan Menjawab dan Tugas:
1. Menjawab pertanyaan umum tentang SPBE secara akurat.
2. Menunjukkan domain, aspek, dan indikator juga level terkait dengan pertanyaan pengguna berdasarkan pedoman SPBE jika pengguna menanyakan indikator/aspek/domain dan level nya juga memberikan alasan pemberian penilaian dari deskripsi ataupun kriteria, bukti lainnya.
3. Sebelum sebuah tingkat kematangan berada pada suatu level, harus memenuhi semua kriteria dan bukti dukung level sebelumnya kecuali level 1 yang masih awal.

## 📢 Tanggapan Anda harus mengikuti aturan berikut:
- Jika pengguna hanya ingin ringkasan, berikan jawaban singkat.
- jawab dengan konkrit tidak terlalu panjang dan jelas.
- Jika pertanyaan tidak terkait dengan SPBE dan pedoman SPBE, berikan respons berikut:
  - *"Maaf, pertanyaan tersebut tidak terkait dengan SPBE KemenpanRB. Saya hanya dapat memberikan jawaban berdasarkan konteks tersebut."
---

## 🔍 Konteks Riwayat Percakapan:


## 🔍 Konteks yang diberikan dari dokumen:
jdih.menpan.go.id
50-
d. Arsitektur SPBE Pemerintah Daerah adalah Arsitektur SPBE yang diterapkan di Pemerintah Daerah.
e. Referensi Arsitektur SPBE adalah kerangka dasar yang mendeskripsikan komponen dasar arsitektur baku yang digunakan sebagai acuan untuk penyusunan setiap Domain Arsitektur SPBE.
f. Domain Arsitektur SPBE adalah kerangka dasar yang mendeskripsikan substansi arsitektur yang memuat domain arsitektur proses bisnis, domain arsitektur data dan informasi, domain arsitektur infrastruktur SPBE, domain arsitektur aplikasi SPBE, domain arsitektur keamanan SPBE, dan domain arsitektur layanan SPBE.
Ketentuan Penilaian: Penilaian dilakukan terhadap bukti dukung dokumen Arsitektur SPBE yang memenuhi kriteria ruang lingkup Referensi Arsitektur dan Domain Arsitektur SPBE dan terdokumentasi secara formal.
Contoh Bukti Dukung: Bukti dukung tingkat kematangan dilampirkan berupa dokumen sesuai huruf b yang mencakup ketentuan huruf c. Data Pendukung dapat disampaikan lebih dari 1 (satu) jenis dokumen.

memberikan panduan dalam pelaksanaan integrasi Proses Bisnis, Data dan Informasi, Infrastruktur SPBE, Aplikasi SPBE, dan Keamanan SPBE untuk menghasilkan Layanan SPBE yang terpadu. c. Referensi Arsitektur dan Domain Arsitektur SPBE terdiri dari: 1. Domain Arsitektur Proses Bisnis; 2. Domain Arsitektur Data dan Informasi; 3. Domain Arsitektur Layanan; 4. Domain Arsitektur Aplikasi; 5. Domain Arsitektur Infrastruktur SPBE; dan, 6. Domain Arsitektur Keamanan SPBE. | | Ketentuan Penilaian: | Penilaian dilakukan terhadap pengaturan/norma yang memenuhi keselarasan referensi Arsitektur SPBE Nasional dan 6 (enam) Domain Arsitektur SPBE melalui kebijakan yang telah ditetapkan. | Penilaian dilakukan terhadap pengaturan/norma yang memenuhi keselarasan referensi Arsitektur SPBE Nasional dan 6 (enam) Domain Arsitektur SPBE melalui kebijakan yang telah ditetapkan. | | ------- | ------------------------ | --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |

Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah sudah memiliki dokumen Arsitektur SPBE atau sudah memiliki konten metadata Arsitektur SPBE pada Sistem Informasi Arsitektur SPBE nasional mutakhir yang mencakup sebagian Referensi Arsitektur dan Domain Arsitektur SPBE Kriteria Bukti Dukung Dokumentasi yang memuat Arsitektur SPBE as-is yang menggambarkan sebagian Referensi Arsitektur SPBE dan Domain Arsitektur SPBE serta telah didokumentasikan secara formal. Level 3 Kriteria Level Kriteria tingkat 2 telah terpenuhi dan dokumen Arsitektur SPBE telah mencakup seluruh referensi dan domain Arsitektur SPBE Instansi Pusat/Pemerintah Daerah (Proses Bisnis, Data dan Informasi, Infrastruktur SPBE, Aplikasi SPBE, Keamanan SPBE, dan Layanan SPBE). Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah memiliki dokumen Arsitektur SPBE mutakhir yang menggambarkan keseluruhan Referensi Arsitektur dan Domain Arsitektur SPBE Kriteria Bukti Dukung Dokumentasi yang memuat Arsitektur SPBE as-is yang didalamnya mencakup seluruh Referensi Arsitektur dan Domain Arsitektur serta telah didokumentasikan secara formal. Level 4 Kriteria Level Kriteria tingkat 3 telah terpenuhi dan dokumen Arsitektur SPBE Instansi Pusat/Pemerintah Daerah telah berpedoman pada Arsitektur SPBE Nasional. Selain itu, dokumen Arsitektur SPBE Instansi Pusat/Pemerintah Daerah telah dilakukan reviu dan evaluasi secara periodik. Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah memiliki dokumen

Tabel 3. Contoh Kaidah Pengisian Penjelasan Pada Domain Manajemen SPBE | Tingkat | Kriteria | *Penjelasan | | ------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------ | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | | 1 | Kegiatan Manajemen Risiko SPBE belum atau telah diterapkan. Kondisi: Kegiatan Manajemen Risiko SPBE diterapkan tanpa program kegiatan yang terarah dan terencana. | Proses manajemen risiko dilakukan sesuai data dukung 21.

jdih.menpan.go.id
87-
Manajemen Risiko SPBE SPBE, bukti undangan rapat penyusunan rancangan penerapan Manajemen Risiko SPBE, dan/atau dokumentasi aktivitas-aktivitas penyusunan Manajemen Risiko SPBE.
Level 2 Kriteria Level Kriteria tingkat 1 telah terpenuhi dan kegiatan Manajemen Risiko SPBE diterapkan dengan program kegiatan yang terarah dan terencana. Kondisi: Penerapan Manajemen Risiko SPBE dilaksanakan tanpa mengacu pada pedoman manajemen risiko SPBE.
Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah sudah menerapkan kegiatan Manajemen Risiko SPBE sesuai dan selaras dengan program kegiatan yang tercantum dalam Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah, namun pelaksanaannya belum mengacu pada pedoman yang berlaku.
Kriteria Bukti Dukung Perencanaan program kerja/aktivitas kegiatan penerapan Manajemen Risiko SPBE tertuang di dalam dokumen Peta Rencana SPBE yang masih berlaku dan terdokumentasi secara formal, namun penerapannya belum mengacu pada pedoman/standar Manajemen Risiko yang telah ditentukan/ditetapkan.
Level 3 Kriteria Level Kriteria tingkat 2 telah terpenuhi dan Manajemen Risiko SPBE telah dilaksanakan dengan mengacu pada pedoman Manajemen Risiko SPBE.
Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah menerapkan Manajemen Risiko SPBE sesuai dengan pedoman Manajemen Risiko SPBE yang berlaku.

## ❓ Pertanyaan pengguna:
Dibawah ini merupakan domain-domain dari Arsitektur SPBE berdasarkan Perpres SPBE, kecuali (pilih salah satu):

- domain arsitektur Proses Bisnis
- domain arsitektur Manajemen SPBE
- domain arsitektur Infrastruktur SPBE
- domain arsitektur Aplikasi SPBE
- domain arsitektur Keamanan SPBE
- domain arsitektur Layanan SPBE


## ✅ Jawaban Anda:


> Finished chain.

> Finished chain.
Domain-domain dari Arsitektur SPBE berdasarkan Perpres SPBE adalah:

1. Domain Arsitektur Proses Bisnis
2. Domain Arsitektur Data dan Informasi
3. Domain Arsitektur Layanan
4. Domain Arsitektur Aplikasi
5. Domain Arsitektur Infrastruktur SPBE
6. Domain Arsitektur Keamanan SPBE

Jadi, jawaban yang benar adalah: **domain arsitektur Manajemen SPBE**.

Alasan: Domain Arsitektur Manajemen SPBE tidak termasuk dalam daftar domain arsitektur SPBE yang ditentukan dalam Perpres SPBE. Domain Manajemen SPBE adalah salah satu domain dalam Sistem Pemerintahan Berbasis Elektronik (SPBE), tetapi tidak termasuk dalam domain arsitektur SPBE.
✅ Question 5 processed successfully
⏳ Menunggu 30 detik...

📊 Dataset RAGAS berhasil disiapkan dengan 5 sampel

--- Sampel 1 ---
Question: Dalam penerapan Manajemen Risiko SPBE, masing-masing IPPD (Instansi Pusat dan Pemerintah Daerah) dapat mengacu pada Pedoman Manajemen Risiko SPBE yang ditetapkan dalam kebijakan:

Context Length: 5141 characters
Response: Dalam penerapan Manajemen Risiko SPBE, masing-masing IPPD (Instansi Pusat dan Pemerintah Daerah) dap...
Reference: PermenPANRB No. 5 Tahun 2020 memberikan pedoman umum bagi Instansi Pusat dan Pemerintah Daerah dalam...

--- Sampel 2 ---
Question: Jika "Rencana dan Anggaran SPBE Instansi Pusat Pemerintah Daerah telah terpadu dan dapat dikendalikan oleh unit kerja/perangkat daerah yang menjalankan fungsi perencanaan dan penganggaran dan telah direviu serta dievaluasi secara periodik:" Maka dapat diberikan level...

Context Length: 11522 characters
Response: Berdasarkan pedoman pemantauan dan evaluasi SPBE, dengan diberikannya informasi tahapan, kriteria pe...
Reference: Berdasarkan pedoman pemantauan dan evaluasi SPBE, dengan diberikannya informasi kriteria-kriteria, m...

--- Sampel 3 ---
Question: Berapa nilai indeks domain yang masih dibawah target pada tahun 2021-2023?
Context Length: 2599 characters
Response: Nilai indeks domain yang masih di bawah target (<2,60) pada tahun 2021-2023 adalah Indeks Domain Tat...
Reference: Nilai indeks domain yang masih di bawah target (<2,60) pada tahun 2021-2023 adalah:

1. Indeks Domai...

--- Sampel 4 ---
Question: Sebuah IPPD melampirkan Peta Rencana SPBE yang telah didokumentasikan secara formal, dan mengklaim memiliki dokumen Peta Rencana SPBE yang telah mengatur seluruh muatan Peta Rencana SPBE Instansi Pusat Pemerintah Daerah. Dokumen Peta Rencana yang diunggah berisikan muatan Peta Rencana secara lengkap antara lain Tata Kelola SPBE, Manajemen SPBE, Layanan SPBE, Arsitektur SPBE, Aplikasi SPBE, Keamanan SPBE dan Audit TIK. Maka level yang pantas diberikan adalah...

Context Length: 13522 characters
Response: Berdasarkan pedoman pemantauan dan evaluasi SPBE, dengan diberikannya informasi tahapan, kriteria pe...
Reference: Berdasarkan pedoman pemantauan dan evaluasi SPBE, dengan diberikannya informasi kriteria-kriteria, m...

--- Sampel 5 ---
Question: Dibawah ini merupakan domain-domain dari Arsitektur SPBE berdasarkan Perpres SPBE, kecuali (pilih salah satu):

- domain arsitektur Proses Bisnis
- domain arsitektur Manajemen SPBE
- domain arsitektur Infrastruktur SPBE
- domain arsitektur Aplikasi SPBE
- domain arsitektur Keamanan SPBE
- domain arsitektur Layanan SPBE

Context Length: 6455 characters
Response: Domain-domain dari Arsitektur SPBE berdasarkan Perpres SPBE adalah:

1. Domain Arsitektur Proses Bis...
Reference: Domain Arsitektur Manajemen SPBE tidak termasuk dalam daftar domain arsitektur SPBE yang ditetapkan ...

In [51]:
print(ragas_dataset)

[{'response': 'Dalam penerapan Manajemen Risiko SPBE, masing-masing IPPD (Instansi Pusat dan Pemerintah Daerah) dapat mengacu pada Pedoman Manajemen Risiko SPBE yang ditetapkan dalam PermenPANRB No. 5/2020.', 'retrieved_contexts': 'INDIKATOR 21\nDomain Aspek Ind Kuesioner D3 A5 ID-21 Tingkat Kematangan Penerapan Manajemen Risiko SPBE. Deskripsi Indikator: a. Manajemen Risiko SPBE adalah pendekatan sistematis yang meliputi proses, pengukuran, struktur, dan budaya untuk menentukan tindakan terbaik terkait Risiko SPBE; b. Risiko SPBE adalah peluang terjadinya suatu peristiwa yang akan mempengaruhi keberhasilan terhadap pencapaian tujuan penerapan SPBE; c. Manajemen Risiko bertujuan untuk menjamin keberlangsungan SPBE dengan meminimalkan dampak risiko dalam SPBE; d. Instansi Pusat dan Pemerintah Daerah menerapkan manajemen risiko SPBE berdasarkan pedoman Manajemen Risiko SPBE. Ketentuan Penilaian: Penilaian dilakukan terhadap bukti dukung penerapan manajemen risiko Instansi Pusat/Pemerintah Daerah yang memenuhi kriteria ruang lingkup, serta terdokumentasi secara formal. Contoh Bukti Dukung: Bukti dukung tingkat kematangan dilampirkan berupa dokumentasi pemenuhan sesuai huruf d. Data Pendukung dapat disampaikan lebih dari 1 (satu) jenis dokumen. Level 1 Kriteria Level Kegiatan Manajemen Risiko SPBE belum atau telah diterapkan. Kondisi: Kegiatan Manajemen Risiko SPBE diterapkan tanpa program kegiatan yang terarah dan terencana. Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah belum atau sudah menerapkan kegiatan Manajemen Risiko SPBE tanpa program kegiatan yang terarah dan terencana. Kriteria Bukti Dukung Draf/rancangan penerapan Manajemen Risiko SPBE, notulensi/catatan penyusunan rancangan penerapan\n\npenerapannya dibuktikan dengan data dukung 21.b. Matrik-Manrisk-SPBE.pdf yaitu form dan matriks hasil pengisian manajemen risiko SPBE pada Pemprov DKI Jakarta (FAKTA). Penerapan manajemen risiko SPBE sudah dilakukan oleh unit kerja/OPD terkait sesuai ketentuan PermenPANRB no.5/2020 namun belum ditetapkan (ANALISIS). | | 4 | Kriteria tingkat 3 telah terpenuhi dan kebijakan strategis Manajemen Risiko SPBE telah ditetapkan oleh Komite Manajemen Risiko SPBE atau Tim KoordinasiSPBE Instansi Pusat/Pemerintah Daerah dan diterapkan ke seluruh unit kerja/perangkat daerah di Instansi Pusat/Pemerintah Daerah. Selain itu, penerapan Manajemen Risiko SPBE telah di dievaluasi secara periodik. | Penerapan Manajemen Risiko SPBE telah dilakukan sesuai ketentuan program strategis kebijakan tata kelola SPBE 21.a. Pergub-Tatakelola-SPBE.pdf pada Pasal 12 Halaman 23 yang kemudian dokumentasi penerapannya telah ditetapkan oleh Koordinator Tim Koordinasi SPBE sesuai data dukung 21.b.SK-Manrisk-SPBE.pdf yang kemudian pelaksanaannya melibatkan seluruh unit kerja/OPD, kemudian sesuai data dukung 21.c. Reviu-Manrisk_SPBE.pdf halaman 30 sudah dilakukan reviu/evaluasi terhadap perkembangan progres tindak lanjut mitigasi risiko/rekomendasi penanganan risiko yang tidak tercapai (FAKTA). Dari data dukung yang disampaikan menggambarkan Penerapan Manajemen SPBE sudah dilakukan secara terprogram dan menyeluruh terhadap seluruh unit kerja/OPD, serta dilakukan reviu/evaluasi (ANALISIS). | | 5 | Kriteria tingkat\n\nKriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah menerapkan Manajemen Risiko SPBE sesuai dengan pedoman Manajemen Risiko SPBE yang berlaku.\nKriteria Bukti Dukung Konteks penerapan Manajemen Risiko SPBE yang menguraikan seluruh pemenuhannya sesuai dengan pedoman/standar Manajemen Risiko yang telah ditentukan/ditetapkan yang terdokumentasi secara formal dan dilengkapi komitmen berupa pakta integritas.\nLevel 4 Kriteria Level Kriteria tingkat 3 telah terpenuhi dan kebijakan strategis Manajemen Risiko SPBE telah ditetapkan oleh Komite Manajemen Risiko SPBE atau Tim Koordinasi SPBE Instansi Pusat/Pemerintah\njdih.menpan.go.id\n88-\n\nKondisi: Manajemen Pengetahuan SPBE telah dilaksanakan tanpa pedoman di Instansi Pusat/Pemerintah Daerah. Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah sudah menerapkan kegiatan Manajemen Pengetahuan SPBE sesuai dan selaras dengan program kegiatan yang tercantum dalam Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah, namun pelaksanaannya belum mengacu pada pedoman yang berlaku. Kriteria Bukti Dukung Perencanaan program kerja/aktivitas kegiatan penerapan Manajemen Pengetahuan SPBE tertuang di dalam dokumen Peta Rencana SPBE yang masih berlaku dan terdokumentasi secara formal, namun penerapannya belum mengacu pada pedoman/standar Manajemen Pengetahuan yang telah ditentukan/ditetapkan. Level 3 Kriteria Level Kriteria tingkat 2 telah terpenuhi, Manajemen Pengetahuan SPBE dilaksanakan dengan mengacu pada pedoman di Instansi Pusat/Pemerintah Daerah dan Manajemen Pengetahuan SPBE diterapkan menggunakan sistem aplikasi manajemen pengetahuan. Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah menerapkan Manajemen Pengetahuan SPBE dan telah tersedia pedoman pelaksanaan manajemen pengetahuan yang disusun sesuai dengan pedoman manajemen pengetahuan SPBE di tingkat nasional, di mana struktur pengelola serta penugasan diuraikan dengan jelas. Selain itu, manajemen pengetahuan SPBE diterapkan menggunakan sistem aplikasi manajemen pengetahuan. Kriteria Bukti Dukung 1. Dokumen pedoman pelaksanaan Manajemen Pengetahuan SPBE Instansi Pusat/Pemerintah Daerah yang', 'reference': 'PermenPANRB No. 5 Tahun 2020 memberikan pedoman umum bagi Instansi Pusat dan Pemerintah Daerah dalam melaksanakan SPBE, termasuk penerapan Manajemen Risiko SPBE\n    ', 'source_documents': [Document(metadata={}, page_content='INDIKATOR 21\nDomain Aspek Ind Kuesioner D3 A5 ID-21 Tingkat Kematangan Penerapan Manajemen Risiko SPBE. Deskripsi Indikator: a. Manajemen Risiko SPBE adalah pendekatan sistematis yang meliputi proses, pengukuran, struktur, dan budaya untuk menentukan tindakan terbaik terkait Risiko SPBE; b. Risiko SPBE adalah peluang terjadinya suatu peristiwa yang akan mempengaruhi keberhasilan terhadap pencapaian tujuan penerapan SPBE; c. Manajemen Risiko bertujuan untuk menjamin keberlangsungan SPBE dengan meminimalkan dampak risiko dalam SPBE; d. Instansi Pusat dan Pemerintah Daerah menerapkan manajemen risiko SPBE berdasarkan pedoman Manajemen Risiko SPBE. Ketentuan Penilaian: Penilaian dilakukan terhadap bukti dukung penerapan manajemen risiko Instansi Pusat/Pemerintah Daerah yang memenuhi kriteria ruang lingkup, serta terdokumentasi secara formal. Contoh Bukti Dukung: Bukti dukung tingkat kematangan dilampirkan berupa dokumentasi pemenuhan sesuai huruf d. Data Pendukung dapat disampaikan lebih dari 1 (satu) jenis dokumen. Level 1 Kriteria Level Kegiatan Manajemen Risiko SPBE belum atau telah diterapkan. Kondisi: Kegiatan Manajemen Risiko SPBE diterapkan tanpa program kegiatan yang terarah dan terencana. Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah belum atau sudah menerapkan kegiatan Manajemen Risiko SPBE tanpa program kegiatan yang terarah dan terencana. Kriteria Bukti Dukung Draf/rancangan penerapan Manajemen Risiko SPBE, notulensi/catatan penyusunan rancangan penerapan'), Document(metadata={}, page_content='penerapannya dibuktikan dengan data dukung 21.b. Matrik-Manrisk-SPBE.pdf yaitu form dan matriks hasil pengisian manajemen risiko SPBE pada Pemprov DKI Jakarta (FAKTA). Penerapan manajemen risiko SPBE sudah dilakukan oleh unit kerja/OPD terkait sesuai ketentuan PermenPANRB no.5/2020 namun belum ditetapkan (ANALISIS). | | 4 | Kriteria tingkat 3 telah terpenuhi dan kebijakan strategis Manajemen Risiko SPBE telah ditetapkan oleh Komite Manajemen Risiko SPBE atau Tim KoordinasiSPBE Instansi Pusat/Pemerintah Daerah dan diterapkan ke seluruh unit kerja/perangkat daerah di Instansi Pusat/Pemerintah Daerah. Selain itu, penerapan Manajemen Risiko SPBE telah di dievaluasi secara periodik. | Penerapan Manajemen Risiko SPBE telah dilakukan sesuai ketentuan program strategis kebijakan tata kelola SPBE 21.a. Pergub-Tatakelola-SPBE.pdf pada Pasal 12 Halaman 23 yang kemudian dokumentasi penerapannya telah ditetapkan oleh Koordinator Tim Koordinasi SPBE sesuai data dukung 21.b.SK-Manrisk-SPBE.pdf yang kemudian pelaksanaannya melibatkan seluruh unit kerja/OPD, kemudian sesuai data dukung 21.c. Reviu-Manrisk_SPBE.pdf halaman 30 sudah dilakukan reviu/evaluasi terhadap perkembangan progres tindak lanjut mitigasi risiko/rekomendasi penanganan risiko yang tidak tercapai (FAKTA). Dari data dukung yang disampaikan menggambarkan Penerapan Manajemen SPBE sudah dilakukan secara terprogram dan menyeluruh terhadap seluruh unit kerja/OPD, serta dilakukan reviu/evaluasi (ANALISIS). | | 5 | Kriteria tingkat'), Document(metadata={}, page_content='Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah menerapkan Manajemen Risiko SPBE sesuai dengan pedoman Manajemen Risiko SPBE yang berlaku.\nKriteria Bukti Dukung Konteks penerapan Manajemen Risiko SPBE yang menguraikan seluruh pemenuhannya sesuai dengan pedoman/standar Manajemen Risiko yang telah ditentukan/ditetapkan yang terdokumentasi secara formal dan dilengkapi komitmen berupa pakta integritas.\nLevel 4 Kriteria Level Kriteria tingkat 3 telah terpenuhi dan kebijakan strategis Manajemen Risiko SPBE telah ditetapkan oleh Komite Manajemen Risiko SPBE atau Tim Koordinasi SPBE Instansi Pusat/Pemerintah\njdih.menpan.go.id\n88-'), Document(metadata={}, page_content='Kondisi: Manajemen Pengetahuan SPBE telah dilaksanakan tanpa pedoman di Instansi Pusat/Pemerintah Daerah. Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah sudah menerapkan kegiatan Manajemen Pengetahuan SPBE sesuai dan selaras dengan program kegiatan yang tercantum dalam Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah, namun pelaksanaannya belum mengacu pada pedoman yang berlaku. Kriteria Bukti Dukung Perencanaan program kerja/aktivitas kegiatan penerapan Manajemen Pengetahuan SPBE tertuang di dalam dokumen Peta Rencana SPBE yang masih berlaku dan terdokumentasi secara formal, namun penerapannya belum mengacu pada pedoman/standar Manajemen Pengetahuan yang telah ditentukan/ditetapkan. Level 3 Kriteria Level Kriteria tingkat 2 telah terpenuhi, Manajemen Pengetahuan SPBE dilaksanakan dengan mengacu pada pedoman di Instansi Pusat/Pemerintah Daerah dan Manajemen Pengetahuan SPBE diterapkan menggunakan sistem aplikasi manajemen pengetahuan. Kriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah menerapkan Manajemen Pengetahuan SPBE dan telah tersedia pedoman pelaksanaan manajemen pengetahuan yang disusun sesuai dengan pedoman manajemen pengetahuan SPBE di tingkat nasional, di mana struktur pengelola serta penugasan diuraikan dengan jelas. Selain itu, manajemen pengetahuan SPBE diterapkan menggunakan sistem aplikasi manajemen pengetahuan. Kriteria Bukti Dukung 1. Dokumen pedoman pelaksanaan Manajemen Pengetahuan SPBE Instansi Pusat/Pemerintah Daerah yang')], 'user_input': 'Dalam penerapan Manajemen Risiko SPBE, masing-masing IPPD (Instansi Pusat dan Pemerintah Daerah) dapat mengacu pada Pedoman Manajemen Risiko SPBE yang ditetapkan dalam kebijakan:\n'}, {'response': 'Berdasarkan pedoman pemantauan dan evaluasi SPBE, dengan diberikannya informasi tahapan, kriteria pemenuhan level dan bukti dukung maka indeks SPBE diberikan: \n\n{ \n  "Penilaian": {\n    "Level": 4,\n    "Indikator": 16,\n    "Aspek": 5,\n    "Domain": 2\n  }\n}\n\nAlasan penilaian diatas karena Rencana dan Anggaran SPBE Instansi Pusat/Pemerintah Daerah telah terpadu dan dapat dikendalikan oleh unit kerja/perangkat daerah yang menjalankan fungsi perencanaan dan penganggaran dan telah direviu serta dievaluasi secara periodik, sesuai dengan kriteria level 4 pada aspek Penerapan Manajemen SPBE (Aspek 5) dan Domain Tata Kelola (Domain 2), dengan indikator 16 yang terkait dengan Tingkat Kematangan Layanan Pusat Data Instansi Pusat/Pemerintah Daerah.', 'retrieved_contexts': 'd. Tidak menerima gratifikasi terkait dengan penugasan sebagai asesor dalam bentuk apapun.\n234-\nB.2. Untuk menerapkan prinsip Objektivitas, Asesor diharapkan:\na. Tidak berpartisipasi dalam kegiatan atau hubungan apapun yang dapat menimbulkan konflik dengan kepentingan penugasannya sebagai asesor, atau yang dapat menimbulkan prasangka, atau yang meragukan kemampuannya untuk dapat melaksanakan tugas dan memenuhi tanggung jawab profesinya secara objektif; b. Tidak menerima sesuatu dalam bentuk apapun yang dapat mengganggu atau patut diduga mengganggu pertimbangan profesionalnya; dan c. Mengungkapkan semua fakta material yang diketahui, yaitu fakta yang jika tidak diungkapkan dapat mengubah atau mempengaruhi penilaian dalam pelaksanaan pemantauan dan evaluasi SPBE.\nB.3. Untuk menerapkan prinsip Kerahasiaan, Asesor diharapkan:\na. Berhati-hati dalam penggunaan dan pelindungan informasi yang diperoleh dalam tugasnya; dan b. Tidak menggunakan informasi untuk keuntungan pribadi atau dengan cara apapun yang akan bertentangan dengan ketentuan atau merugikan tujuan pelaksanaan pemantauan dan evaluasi SPBE yang sah dan etis.\nB.4. Untuk menerapkan prinsip Kompetensi, Asesor diharapkan:\na. Memberikan kontribusi pelaksanaan tugas sesuai dengan pengetahuan, keahlian dan keterampilan, serta pengalaman yang diperlukan; dan b. Melakukan kegiatan pemantauan dan evaluasi SPBE sesuai dengan ketentuan yang berlaku.\n\nNamun disisi lain, Badan xxx masih terdapat beberapa kelemahan, khususnya pada aspek Layanan Publik. Layanan Publik memang sudah direncanakan pada Arsitektur SPBE dan Peta Rencana SPBE dan berdasarkan penerapan Rencana dan Anggaran SPBE sudah terakomodasi, namun pada penerapannya, kapabilitas fungsi teknis dari layanan tersebut masih rendah, dimana masih banyak aplikasi publik yang dibangun secara sendiri-sendiri, sehingga tidak memanfaatkan potensi transaksi dan integrasi terhadap layanan SPBE lainnya. Hal ini menyebabkan Layanan Publik yang diberikan tidak efektif dan optimal pemanfaatannya\nPada Aspek Kebijakan Layanan yang masih bersifat mengatur secara internal perlu ditingkatkan untuk mengakomodasi arah kolaborasi dan integrasi serta dapat ditingkatkan sesuai kebutuhan Badan xxx. Aspek Layanan Publik yang tingkat kematangannya masih rendah, agar dapat menggunakan aplikasi umum berbagi pakai yang telah tetapkan secara nasional, atau melakukan replikasi dari layanan-layanan publik sejenis yang dibangun oleh Instansi lainnya. Diharapkan dapat melakukan inisiatif penerapan Manajemen SPBE sesuai dengan Peraturan yang berlaku, sehingga pada pelaksanaan evaluasi SPBE selanjutnya sudah dapat memenuhi indikator dan kriteria penilaian sesuai target\nG. Tata Cara dan Kaidah Penyusunan Hasil Reviu Bagi Tim Reviu.\n\nCatatan Penilaian Visit\nKlarifikasi tidak dilakukan terhadap Indikator <<No, dan Subste Berdasarkan hasil verifikasi <\nGambar 4. Penilaian Visitasi Pada Aplikasi\nAsesor Eksternal dapat melakukan klarifikasi, verifikasi, dan validasi kepada Asesor Internal terhadap indikator yang memerlukan perincian dan data dukung tambahan. Dalam memberikan penjelasan dalam penilaian, Asesor Eksternal agar mengacu pada kaidah berikut ini, sehingga uraian hasil penilaian eksternal terdokumentasi dan dapat dipertanggung jawabkan. Penulisan penjelasan pada masing-masing Domain dapat menyesuaikan karakteristik penilaian dan kriteria tingkat kematangannya. Berikut ini\njdih.menpan.go.id\n223-\nmerupakan contoh kaidah dalam memberikan penjelasan penilaian visitasi pada aplikasi pemantauan dan evaluasi SPBE bagi Asesor Eksternal.\nKaidah Penulisan Penjelasan Penilaian Visitasi Bagi Asesor Eksternal yang Melakukan Klarifikasi/Koreksi Pada Domain Kebijakan, Domain Tata Kelola, Domain Manajemen, dan Domain Layanan (Indikator 1-47).\nKlarifikasi telah dilakukan terhadap Indikator <\nBerdasarkan penjelasan dan data dukung tambahan yang disampaikan pada saat visitasi, maka <\nHasil penilaian visitasi menggambarkan<\nBerikut ini merupakan salah satu contoh uraian penjelasan pada salah satu indikator yang dilakukan klarifikasi/koreksi pada penilaian visitasi, yaitu pada Indikator 16 Tingkat Kematangan Layanan Pusat Data Instansi Pusat/ Pemerintah Daerah:\n\njdih.menpan.go.id\n58-\nanggaran SPBE yang seluruhnya telah dikonsultasikan dengan unit pengelola TIK dan didokumentasikan secara formal.\nLevel 4 Kriteria Level Kriteria tingkat 3 telah terpenuhi. Seluruh Rencana dan Anggaran SPBE Instansi Pusat/Pemerintah Daerah telah terpadu dan dapat dikendalikan oleh unit kerja/perangkat daerah yang menjalankan fungsi perencanaan dan penganggaran. Selain itu, Rencana dan Anggaran SPBE telah direviu dan dievaluasi secara periodik.\nKriteria pemenuhan Level Seluruh Rencana dan Anggaran SPBE Instansi Pusat/Pemerintah Daerah telah terpadu dan terkendali pada unit kerja/perangkat daerah yang menjalankan fungsi perencanaan dan penganggaran di Instansi Pusat/Pemerintah Daerah yang dituangkan dalam rencana kerja dan anggaran dan telah dilakukan reviu dan/atau evaluasi secara periodik.\nKriteria Bukti Dukung 1) Dokumen SOP terkait proses penyusunan Anggaran SPBE terpadu dan/atau Dokumen RKA/KL atau DPA-SKPD terkait Rencana dan Anggaran SPBE terpadu yang dikendalikan oleh unit kerja/perangkat daerah yang menjalankan fungsi perencanaan dan penganggaran dan didokumentasikan secara formal;\n2) Terdapat notulensi/catatan/laporan hasil evaluasi/reviu terkait Rencana dan Anggaran SPBE yang masih berlaku (<2 tahun);\n3) Hasil evaluasi/reviu yang berisi konten isu/permasalahan dan rekomendasi perbaikan yang aktual; dan\n\njdih.menpan.go.id\n106-\nDaerah melalui pemanfaatan sistem aplikasi manajemen pengetahuan SPBE.\nLevel 4 Kriteria Level Kriteria tingkat 3 telah terpenuhi, semua unit kerja/perangkat daerah telah menerapkan Manajemen Pengetahuan SPBE dengan menggunakan sistem aplikasi manajemen pengetahuan yang terintegrasi serta telah dilakukan reviu dan evaluasi terhadap penerapan Manajemen Pengetahuan SPBE.\nKriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah menerapkan Manajemen Pengetahuan SPBE di seluruh unit kerja/perangkat daerah dengan memanfaatkan aplikasi sistem manajemen pengetahuan SPBE yang telah terintegrasi dengan sistem manajemen pengetahuan SPBE di tingkat nasional, serta telah dilakukan reviu dan/atau evaluasi secara berkala.\nKriteria Bukti Dukung 1) Konteks penerapan Manajemen Pengetahuan yang menguraikan seluruh pemenuhannya sesuai dengan pedoman/standar Manajemen Pengetahuan yang telah ditentukan/ditetapkan dan terdokumentasi secara formal.\n2) Bukti hasil penerapan manajemen pengetahuan berupa pengetahuan-pengetahuan baru yang telah dibagi pakai.\n3) Terdapat notulensi/catatan/laporan hasil reviu/evaluasi terkait penerapan Manajemen Pengetahuan SPBE yang masih berlaku (<2 tahun).\n4) Hasil reviu/evaluasi yang berisi konten isu/permasalahan dan rekomendasi perbaikan yang aktual.\n5) Bukti undangan rapat reviu/evaluasi penerapan Manajemen Pengetahuan SPBE, dan/atau dokumentasi aktivitas-aktivitas evaluasi penerapan Manajemen Pengetahuan SPBE (opsional).\n\nKriteria pemenuhan Level Instansi Pusat/Pemerintah Daerah telah memiliki dokumen Peta Rencana SPBE yang dituangkan dalam rencana kerja dan anggaran dan telah dilakukan reviu dan/atau evaluasi secara periodik. Kriteria Bukti Dukung 1) Dokumen yang memuat Peta Rencana SPBE yang didalamnya mencakup seluruh muatan Peta Rencana SPBE dan Dokumen Rencana Kerja dan Anggaran 3 (tiga) tahun terakhir yang didalamnya tercantum program/kegiatan yang selaras dengan Peta Rencana SPBE tersebut; 2) Terdapat notulensi/catatan/laporan hasil evaluasi/reviu terkait Peta Rencana SPBE yang masih berlaku (<2 tahun); 3) Hasil evaluasi/reviu yang berisi konten isu/permasalahan dan rekomendasi perbaikan yang aktual; dan 4) Bukti undangan rapat evaluasi Peta Rencana SPBE, dan/atau dokumentasi aktivitas-aktivitas evaluasi Peta Rencana SPBE (opsional). Level 5 Kriteria Level Kriteria tingkat 4 telah terpenuhi dan dokumen Peta Rencana SPBE Instansi Pusat/Pemerintah Daerah telah dilakukan pemutakhiran sebagai tindak lanjut hasil reviu dan evaluasi. Kriter

In [ ]:
# Konversi ke DataFrame
import pandas as pd # type: ignore
df = pd.DataFrame(ragas_dataset)
df

,response,retrieved_contexts,reference,source_documents,user_input
0,"Dalam penerapan Manajemen Risiko SPBE, masing-...",INDIKATOR 21\nDomain Aspek Ind Kuesioner D3 A5...,PermenPANRB No. 5 Tahun 2020 memberikan pedoma...,[page_content='INDIKATOR 21\nDomain Aspek Ind ...,"Dalam penerapan Manajemen Risiko SPBE, masing-..."
1,Berdasarkan pedoman pemantauan dan evaluasi SP...,d. Tidak menerima gratifikasi terkait dengan p...,Berdasarkan pedoman pemantauan dan evaluasi SP...,[page_content='d. Tidak menerima gratifikasi t...,"Jika ""Rencana dan Anggaran SPBE Instansi Pusat..."
2,Nilai indeks domain yang masih di bawah target...,Berdasarkan capaian Indeks SPBE Nasional sebag...,Nilai indeks domain yang masih di bawah target...,[page_content='Berdasarkan capaian Indeks SPBE...,Berapa nilai indeks domain yang masih dibawah ...
3,Berdasarkan pedoman pemantauan dan evaluasi SP...,d. Tidak menerima gratifikasi terkait dengan p...,Berdasarkan pedoman pemantauan dan evaluasi SP...,[page_content='d. Tidak menerima gratifikasi t...,Sebuah IPPD melampirkan Peta Rencana SPBE yang...
4,Domain-domain dari Arsitektur SPBE berdasarkan...,jdih.menpan.go.id\n50-\nd. Arsitektur SPBE Pem...,Domain Arsitektur Manajemen SPBE tidak termasu...,[page_content='jdih.menpan.go.id\n50-\nd. Arsi...,Dibawah ini merupakan domain-domain dari Arsit...

In [53]:
# Buat list baru dengan urutan dan filter kolom yang diinginkan
ragas_dataset_filtered = [
    {
        "user_input": item["user_input"],
        "retrieved_contexts": item["retrieved_contexts"],
        "response": item["response"],
        "reference": item["reference"]
    }
    for item in ragas_dataset
]

for item in ragas_dataset_filtered:
    if isinstance(item["retrieved_contexts"], str):
        item["retrieved_contexts"] = item["retrieved_contexts"].split("\n\n")

In [54]:
df_ragas = pd.DataFrame(ragas_dataset_filtered, columns=["user_input", "retrieved_contexts", "response", "reference"])
df_ragas.to_csv("spbe2_test_vector_ragas.csv")

In [55]:
import pickle
with open("vector2_ragas_dataset_filtered.pkl", "wb") as f:
    pickle.dump(ragas_dataset_filtered, f)

In [56]:
import pickle
with open("vector2_ragas_dataset_filtered.pkl", "rb") as f:
    ragas_dataset_filtered = pickle.load(f)

In [ ]:
# Load environment variables from .env file
load_dotenv()
import pandas as pd # type: ignore
from langchain_groq import ChatGroq # type: ignore
from ragas import evaluate, EvaluationDataset # type: ignore
from ragas.run_config import RunConfig # type: ignore
from ragas.llms import LangchainLLMWrapper # type: ignore
from ragas.embeddings import LangchainEmbeddingsWrapper # type: ignore
from langchain_openai import AzureChatOpenAI, AzureOpenAIEmbeddings # type: ignore
from ragas.metrics import ( # type: ignore
    faithfulness,  
    answer_relevancy, 
    context_recall, 
    context_precision
    ) 

eval_dataset = EvaluationDataset.from_list(ragas_dataset_filtered)

embeddings_ollama = OllamaEmbeddings(
    model="nomic-embed-text:latest",
)

# Integration Azure Open AI in Langchain
llm_openai_azure = AzureChatOpenAI(
    openai_api_key=os.environ.get("AZURE_OPENAI_API_KEY"),
    azure_endpoint=os.environ.get("AZURE_OPENAI_ENDPOINT"),
    deployment_name=os.environ.get("41_AZURE_OPENAI_DEPLOYMENT"),
    openai_api_version=os.environ.get("41_AZURE_OPENAI_API_VERSION"),
)

# llm2_groqcloud = ChatGroq(
#     model_name="llama-3.3-70b-versatile",
#     temperature=0,
#     groq_api_key=os.getenv("GROQ_API_KEY_RAGAS_REGIMR"),
# )

evaluator_embedding = LangchainEmbeddingsWrapper(embeddings_ollama)
evaluator_llm = LangchainLLMWrapper(llm_openai_azure)

# Evaluasi dengan RAGAS
results = evaluate(
    dataset=eval_dataset,
    metrics=[
        faithfulness,
        answer_relevancy,
        context_recall,
        context_precision
    ],
    llm=evaluator_llm,
    embeddings=evaluator_embedding,
)

print("📊 Hasil Evaluasi RAGAS:")
results_df = results.to_pandas()
results_df.to_csv("evaluation2_spbe_vector.csv", index=False)
print(results_df)

Evaluating:   0%|          | 0/20 [00:00<?, ?it/s]

📊 Hasil Evaluasi RAGAS:
                                          user_input  \
0  Dalam penerapan Manajemen Risiko SPBE, masing-...
1  Jika "Rencana dan Anggaran SPBE Instansi Pusat...
2  Berapa nilai indeks domain yang masih dibawah ...
3  Sebuah IPPD melampirkan Peta Rencana SPBE yang...
4  Dibawah ini merupakan domain-domain dari Arsit...

                                  retrieved_contexts  \
0  [INDIKATOR 21\nDomain Aspek Ind Kuesioner D3 A...
1  [d. Tidak menerima gratifikasi terkait dengan ...
2  [Berdasarkan capaian Indeks SPBE Nasional seba...
3  [d. Tidak menerima gratifikasi terkait dengan ...
4  [jdih.menpan.go.id\n50-\nd. Arsitektur SPBE Pe...

                                            response  \
0  Dalam penerapan Manajemen Risiko SPBE, masing-...
1  Berdasarkan pedoman pemantauan dan evaluasi SP...
2  Nilai indeks domain yang masih di bawah target...
3  Berdasarkan pedoman pemantauan dan evaluasi SP...
4  Domain-domain dari Arsitektur SPBE berdasarkan...

                                           reference  faithfulness  \
0  PermenPANRB No. 5 Tahun 2020 memberikan pedoma...      0.500000
1  Berdasarkan pedoman pemantauan dan evaluasi SP...      0.777778
2  Nilai indeks domain yang masih di bawah target...      1.000000
3  Berdasarkan pedoman pemantauan dan evaluasi SP...      0.600000
4  Domain Arsitektur Manajemen SPBE tidak termasu...      0.750000

   answer_relevancy  context_recall  context_precision
0          0.936441        1.000000           0.500000
1          0.678468        0.142857           0.469286
2          0.748882        1.000000           0.500000
3          0.762038        1.000000           0.444577
4          0.939570        1.000000           1.000000

In [58]:
results_df

,user_input,retrieved_contexts,response,reference,faithfulness,answer_relevancy,context_recall,context_precision
0,"Dalam penerapan Manajemen Risiko SPBE, masing-...",[INDIKATOR 21\nDomain Aspek Ind Kuesioner D3 A...,"Dalam penerapan Manajemen Risiko SPBE, masing-...",PermenPANRB No. 5 Tahun 2020 memberikan pedoma...,0.500000,0.936441,1.000000,0.500000
1,"Jika ""Rencana dan Anggaran SPBE Instansi Pusat...",[d. Tidak menerima gratifikasi terkait dengan ...,Berdasarkan pedoman pemantauan dan evaluasi SP...,Berdasarkan pedoman pemantauan dan evaluasi SP...,0.777778,0.678468,0.142857,0.469286
2,Berapa nilai indeks domain yang masih dibawah ...,[Berdasarkan capaian Indeks SPBE Nasional seba...,Nilai indeks domain yang masih di bawah target...,Nilai indeks domain yang masih di bawah target...,1.000000,0.748882,1.000000,0.500000
3,Sebuah IPPD melampirkan Peta Rencana SPBE yang...,[d. Tidak menerima gratifikasi terkait dengan ...,Berdasarkan pedoman pemantauan dan evaluasi SP...,Berdasarkan pedoman pemantauan dan evaluasi SP...,0.600000,0.762038,1.000000,0.444577
4,Dibawah ini merupakan domain-domain dari Arsit...,[jdih.menpan.go.id\n50-\nd. Arsitektur SPBE Pe...,Domain-domain dari Arsitektur SPBE berdasarkan...,Domain Arsitektur Manajemen SPBE tidak termasu...,0.750000,0.939570,1.000000,1.000000

In [ ]:
# results_df.to_csv("results_spbe_vector_ragas.csv")